import { TransactionCanceledException } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, QueryCommand, ScanCommand, TransactWriteCommand, UpdateCommand, type TransactWriteCommandInput } from '@aws-sdk/lib-dynamodb';
import type { DeliveryListOptions, DeliveryRepository } from '../domain/delivery.repository.js';
import { DeliveryConflictError } from '../domain/delivery.repository.js';
import type { DeliveryEvidence, DeliveryReceipt } from '../domain/delivery.js';
export class DynamoDbDeliveryRepository implements DeliveryRepository {
  constructor(private readonly c:DynamoDBDocumentClient,private readonly table:string,private readonly tripsTable:string,private readonly trucksTable:string,private readonly loadsTable:string){}
  async nextNumber(year:number){const r=await this.c.send(new UpdateCommand({TableName:this.table,Key:{pk:`COUNTER#${year}`},UpdateExpression:'ADD #value :one',ExpressionAttributeNames:{'#value':'value'},ExpressionAttributeValues:{':one':1},ReturnValues:'UPDATED_NEW'}));return `ENT-${year}-${String(Number(r.Attributes?.['value'])).padStart(6,'0')}`;}
  async findById(id:string){const r=await this.c.send(new GetCommand({TableName:this.table,Key:{pk:`DELIVERY#${id}`},ConsistentRead:true}));return r.Item?.['data'] as DeliveryReceipt??null;}
  async findByTripId(tripId:string){const r=await this.c.send(new QueryCommand({TableName:this.table,IndexName:'RelationIndex',KeyConditionExpression:'relationPk=:pk',ExpressionAttributeValues:{':pk':`TRIP#${tripId}`},ScanIndexForward:false}));const all=(r.Items??[]).map(x=>x['data'] as DeliveryReceipt);return all.find(x=>x.status!=='VOIDED')??all[0]??null;}
  async list(o:DeliveryListOptions){const r=await this.c.send(new ScanCommand({TableName:this.table,Limit:o.limit,FilterExpression:'entityType=:e',ExpressionAttributeValues:{':e':'DELIVERY'},...(o.nextToken?{ExclusiveStartKey:JSON.parse(Buffer.from(o.nextToken,'base64url').toString())as Record<string,unknown>}:{})}));const items=(r.Items??[]).map(x=>x['data']as DeliveryReceipt).filter(x=>(!o.saleId||x.saleId===o.saleId)&&(!o.status||x.status===o.status));return{items,...(r.LastEvaluatedKey?{nextToken:Buffer.from(JSON.stringify(r.LastEvaluatedKey)).toString('base64url')}:{})};}
  async create(d:DeliveryReceipt){await this.write([{Put:{TableName:this.table,Item:item(d),ConditionExpression:'attribute_not_exists(pk)'}},{Put:{TableName:this.table,Item:{pk:`NUMBER#${d.deliveryNumber}`,entityType:'NUMBER',deliveryId:d.id},ConditionExpression:'attribute_not_exists(pk)'}},{Put:{TableName:this.table,Item:{pk:`ACTIVE_TRIP#${d.tripId}`,entityType:'ACTIVE_TRIP',deliveryId:d.id},ConditionExpression:'attribute_not_exists(pk)'}}]);}
  async update(d:DeliveryReceipt,e:string){await this.write([{Put:{TableName:this.table,Item:item(d),ConditionExpression:'updatedAt=:e AND #data.#status=:draft',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':e,':draft':'DRAFT'}}}]);}
  async confirm(d:DeliveryReceipt,trip:Parameters<DeliveryRepository['confirm']>[1],truck:Parameters<DeliveryRepository['confirm']>[2],load:Parameters<DeliveryRepository['confirm']>[3],e:string,tripExpected:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(d),ConditionExpression:'updatedAt=:e AND #data.#status=:draft',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':e,':draft':'DRAFT'}}},{Put:{TableName:this.tripsTable,Item:tripItem(trip),ConditionExpression:'updatedAt=:e',ExpressionAttributeValues:{':e':tripExpected}}},{Delete:{TableName:this.tripsTable,Key:{pk:`ACTIVE_TRUCK#${trip.truckId}`}}},{Delete:{TableName:this.tripsTable,Key:{pk:`ACTIVE_DRIVER#${trip.driverId}`}}},{Put:{TableName:this.trucksTable,Item:truckItem(truck),ConditionExpression:'#data.currentOdometerKm <= :km',ExpressionAttributeNames:{'#data':'data'},ExpressionAttributeValues:{':km':truck.currentOdometerKm}}}];for(const line of d.lines)tx.push({Update:{TableName:this.loadsTable,Key:{pk:`BALANCE#${d.saleId}#${line.saleItemId}`},UpdateExpression:'SET deliveredQuantityBaseInternal=if_not_exists(deliveredQuantityBaseInternal,:zero)+:delivered, updatedAt=:updated ADD allocatedQuantityBaseInternal :released, #version :one',ConditionExpression:'allocatedQuantityBaseInternal >= :loaded AND (attribute_not_exists(deliveredQuantityBaseInternal) OR deliveredQuantityBaseInternal + :delivered <= soldQuantityBaseInternal)',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':zero':0,':delivered':line.deliveredQuantityBaseInternal,':released':-line.loadedQuantityBaseInternal,':loaded':line.loadedQuantityBaseInternal,':updated':d.updatedAt,':one':1}}});await this.write(tx);}
  async void(d:DeliveryReceipt,e:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(d),ConditionExpression:'updatedAt=:e AND #data.#status=:confirmed',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':e,':confirmed':'CONFIRMED'}}},{Delete:{TableName:this.table,Key:{pk:`ACTIVE_TRIP#${d.tripId}`}}}];for(const line of d.lines)tx.push({Update:{TableName:this.loadsTable,Key:{pk:`BALANCE#${d.saleId}#${line.saleItemId}`},UpdateExpression:'SET updatedAt=:updated ADD deliveredQuantityBaseInternal :q, #version :one',ConditionExpression:'deliveredQuantityBaseInternal >= :positive',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':updated':d.updatedAt,':q':-line.deliveredQuantityBaseInternal,':positive':line.deliveredQuantityBaseInternal,':one':1}}});await this.write(tx);}
  async addEvidence(x:DeliveryEvidence){await this.write([{Put:{TableName:this.table,Item:{pk:`EVIDENCE#${x.id}`,entityType:'EVIDENCE',relationPk:`DELIVERY#${x.deliveryReceiptId}`,relationSk:`EVIDENCE#${x.createdAt}#${x.id}`,data:x},ConditionExpression:'attribute_not_exists(pk)'}}]);}
  async evidenceByDelivery(id:string){const r=await this.c.send(new QueryCommand({TableName:this.table,IndexName:'RelationIndex',KeyConditionExpression:'relationPk=:pk AND begins_with(relationSk,:sk)',ExpressionAttributeValues:{':pk':`DELIVERY#${id}`,':sk':'EVIDENCE#'}}));return(r.Items??[]).map(x=>x['data']as DeliveryEvidence);}
  async findEvidence(id:string){const r=await this.c.send(new GetCommand({TableName:this.table,Key:{pk:`EVIDENCE#${id}`},ConsistentRead:true}));return r.Item?.['data']as DeliveryEvidence??null;}
  private async write(x:NonNullable<TransactWriteCommandInput['TransactItems']>){try{await this.c.send(new TransactWriteCommand({TransactItems:x}));}catch(e){if(e instanceof TransactionCanceledException)throw new DeliveryConflictError();throw e;}}
}
function item(d:DeliveryReceipt){return{pk:`DELIVERY#${d.id}`,entityType:'DELIVERY',updatedAt:d.updatedAt,relationPk:`TRIP#${d.tripId}`,relationSk:`DELIVERY#${d.createdAt}`,salePk:`SALE#${d.saleId}`,datePk:'DELIVERY',dateSk:`${d.createdAt}#${d.id}`,statusPk:`STATUS#${d.status}`,statusSk:`${d.createdAt}#${d.id}`,data:d};}
function tripItem(t:Parameters<DeliveryRepository['confirm']>[1]){return{pk:`TRIP#${t.id}`,entityType:'TRIP',updatedAt:t.updatedAt,data:t};}
function truckItem(t:Parameters<DeliveryRepository['confirm']>[2]){return{pk:`TRUCK#${t.id}`,entityType:'TRUCK',status:t.status,vehicleType:t.vehicleType,fuelType:t.fuelType,normalizedSearch:t.normalizedSearch,data:t};}
