import{TransactionCanceledException}from'@aws-sdk/client-dynamodb';import{DynamoDBDocumentClient,GetCommand,PutCommand,QueryCommand,ScanCommand,TransactWriteCommand}from'@aws-sdk/lib-dynamodb';import type{CostingRepository}from'../domain/costing.repository.js';import{CostingConflictError}from'../domain/costing.repository.js';import type{LotCostBalance,SaleLotAllocation}from'../domain/costing.js';
export class DynamoDbCostingRepository implements CostingRepository{constructor(private readonly client:DynamoDBDocumentClient,private readonly tableName:string){}
 async getBalance(id:string){const r=await this.client.send(new GetCommand({TableName:this.tableName,Key:{pk:`LOT_BALANCE#${id}`},ConsistentRead:true}));return r.Item?r.Item['data']as LotCostBalance:null;}
 async putBalanceIfAbsent(b:LotCostBalance){try{await this.client.send(new PutCommand({TableName:this.tableName,Item:balanceRecord(b),ConditionExpression:'attribute_not_exists(pk)'}));}catch(e){if(!(e instanceof TransactionCanceledException)&&e instanceof Error&&e.name!=='ConditionalCheckFailedException')throw e;}}
 async openLots(productId:string){const items:LotCostBalance[]=[];let key:Record<string,unknown>|undefined;do{const r=await this.client.send(new QueryCommand({TableName:this.tableName,IndexName:'OpenLotsIndex',KeyConditionExpression:'openPartition = :p',ExpressionAttributeValues:{':p':`OPENLOT#PRODUCT#${productId}`},ScanIndexForward:true,Limit:100,...(key?{ExclusiveStartKey:key}:{})}));items.push(...(r.Items??[]).map(i=>i['data']as LotCostBalance));key=r.LastEvaluatedKey;}while(key);return items;}
 async allocationsBySale(id:string){const r=await this.client.send(new QueryCommand({TableName:this.tableName,IndexName:'SaleAllocationsIndex',KeyConditionExpression:'saleId = :id',ExpressionAttributeValues:{':id':id},ConsistentRead:false,Limit:100}));return(r.Items??[]).map(i=>i['data']as SaleLotAllocation);}
 async allocate(a:SaleLotAllocation,b:LotCostBalance,v:number){try{await this.client.send(new TransactWriteCommand({TransactItems:[{Put:{TableName:this.tableName,Item:balanceRecord(b),ConditionExpression:'#version = :v AND remainingQuantityBaseInternal >= :take',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':v':v,':take':a.quantityBaseInternal}}},{Put:{TableName:this.tableName,Item:allocationRecord(a),ConditionExpression:'attribute_not_exists(pk)'}}]}));}catch(e){if(e instanceof TransactionCanceledException)throw new CostingConflictError();throw e;}}
 async reverseSale(id:string,actor:string,reason:string,at:string){for(const allocation of await this.allocationsBySale(id)){if(allocation.status!=='ACTIVE')continue;for(let n=0;n<3;n++){const b=await this.getBalance(allocation.lotId);if(!b)throw new CostingConflictError();const next:LotCostBalance={...b,allocatedQuantityBaseInternal:b.allocatedQuantityBaseInternal-allocation.quantityBaseInternal,remainingQuantityBaseInternal:b.remainingQuantityBaseInternal+allocation.quantityBaseInternal,allocatedCostGuarani:b.allocatedCostGuarani-allocation.costGuarani,version:b.version+1,updatedAt:at};const reversed:SaleLotAllocation={...allocation,status:'REVERSED',reversedAt:at,reversedBy:actor,reversalReason:reason};try{await this.client.send(new TransactWriteCommand({TransactItems:[{Put:{TableName:this.tableName,Item:balanceRecord(next),ConditionExpression:'#version = :v',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':v':b.version}}},{Put:{TableName:this.tableName,Item:allocationRecord(reversed),ConditionExpression:'#status = :active',ExpressionAttributeNames:{'#status':'status'},ExpressionAttributeValues:{':active':'ACTIVE'}}}]}));break;}catch(e){if(!(e instanceof TransactionCanceledException)||n===2)throw new CostingConflictError();}}}}
 async allBalances(){return this.scan<LotCostBalance>('LOT_BALANCE');}async allAllocations(){return this.scan<SaleLotAllocation>('ALLOCATION');}async replaceBalance(b:LotCostBalance){await this.client.send(new PutCommand({TableName:this.tableName,Item:balanceRecord(b)}));}
 private async scan<T>(entity:string){const items:T[]=[];let key:Record<string,unknown>|undefined;do{const r=await this.client.send(new ScanCommand({TableName:this.tableName,FilterExpression:'entityType = :e',ExpressionAttributeValues:{':e':entity},Limit:100,...(key?{ExclusiveStartKey:key}:{})}));items.push(...(r.Items??[]).map(i=>i['data']as T));key=r.LastEvaluatedKey;}while(key);return items;}
}
function balanceRecord(b:LotCostBalance){return{pk:`LOT_BALANCE#${b.lotId}`,entityType:'LOT_BALANCE',productId:b.productId,remainingQuantityBaseInternal:b.remainingQuantityBaseInternal,version:b.version,...(b.remainingQuantityBaseInternal>0?{openPartition:`OPENLOT#PRODUCT#${b.productId}`,openSort:`${b.receivedAt}#${b.lotNumber}`} :{}),data:b};}
function allocationRecord(a:SaleLotAllocation){return{pk:`ALLOCATION#${a.id}`,entityType:'ALLOCATION',saleId:a.saleId,lotId:a.lotId,status:a.status,allocSort:`${a.saleItemId}#${a.lotReceivedAt}#${a.lotNumber}`,data:a};}
