import { randomUUID } from 'node:crypto';
import type { SaleItemDeliveryBalanceResponse, SaveTripLoadRequest, TripLoadResponse, UserRole } from '@lcm/contracts';
import type { ProductRepository } from '../../products/domain/product.repository.js';
import type { SaleRepository } from '../../sales/domain/sale.repository.js';
import type { TripRepository } from '../../trips/domain/trip.repository.js';
import type { TruckRepository } from '../../trucks/domain/truck.repository.js';
import type { DriverRepository } from '../../drivers/domain/driver.repository.js';
import type { TripLoad } from '../domain/trip-load.js';
import type { TripLoadRepository } from '../domain/trip-load.repository.js';
import { TripLoadConflictError } from '../domain/trip-load.repository.js';
export class TripLoadsService {
 constructor(private readonly repo:TripLoadRepository,private readonly trips:TripRepository,private readonly sales:SaleRepository,private readonly products:ProductRepository,private readonly trucks:TruckRepository,private readonly drivers:DriverRepository){}
 async get(tripId:string,userId:string,role:UserRole){await this.access(tripId,userId,role);return this.repo.findByTripId(tripId);}
 async balances(tripId:string,userId:string,role:UserRole):Promise<readonly SaleItemDeliveryBalanceResponse[]>{const trip=await this.access(tripId,userId,role);if(!trip.saleId)throw bad('El viaje no tiene venta asociada');const sale=await this.sales.findById(trip.saleId);if(!sale)throw notFound('Venta no encontrada');return Promise.all(sale.items.map(async i=>{const b=await this.repo.getBalance(sale.id,i.id);return({saleItemId:i.id,productId:i.productId,productName:i.productSnapshot.name,quantityScale:i.productSnapshot.quantityScale,soldQuantityBaseInternal:i.quantityBaseInternal,allocatedQuantityBaseInternal:b.allocated,remainingQuantityBaseInternal:i.quantityBaseInternal-b.allocated-b.delivered});}));}
 async save(tripId:string,input:SaveTripLoadRequest,userId:string):Promise<TripLoadResponse>{const trip=await this.trip(tripId);if(trip.status!=='DRAFT')throw conflict('La carga solo se edita en viaje borrador');if(!trip.saleId)throw bad('El viaje no tiene venta asociada');const sale=await this.sales.findById(trip.saleId);if(!sale||sale.status!=='CONFIRMED')throw conflict('La venta debe estar confirmada');const existing=await this.repo.findByTripId(tripId);if(existing&&existing.status!=='DRAFT')throw conflict('La carga ya no es editable');if(input.lines.length===0)throw bad('Agregue al menos una línea');const seen=new Set<string>();const lines=[];for(const x of input.lines){if(seen.has(x.saleItemId))throw bad('No repita un ítem de venta');seen.add(x.saleItemId);if(!Number.isSafeInteger(x.quantityBaseInternal)||x.quantityBaseInternal<=0)throw bad('Cantidad inválida');const item=sale.items.find(i=>i.id===x.saleItemId);if(!item)throw bad('Ítem ajeno a la venta');const product=await this.products.findById(item.productId);if(!product)throw bad('Producto no encontrado');const weight=product.weightPerBaseUnitGrams===undefined?undefined:Math.round(x.quantityBaseInternal*product.weightPerBaseUnitGrams/product.quantityScale);const volume=product.baseUnit==='M3'?Math.round(x.quantityBaseInternal*1_000_000/product.quantityScale):product.volumePerBaseUnitMl===undefined?undefined:Math.round(x.quantityBaseInternal*product.volumePerBaseUnitMl/product.quantityScale);lines.push({id:existing?.lines.find(l=>l.saleItemId===x.saleItemId)?.id??randomUUID(),saleItemId:item.id,productId:item.productId,productCode:item.productSnapshot.code,productName:item.productSnapshot.name,baseUnit:item.productSnapshot.baseUnit,quantityScale:item.productSnapshot.quantityScale,quantityBaseInternal:x.quantityBaseInternal,...(weight===undefined?{}:{estimatedWeightGrams:weight}),...(volume===undefined?{}:{estimatedVolumeMl:volume})});}
 for(const l of lines){const sold=sale.items.find(i=>i.id===l.saleItemId)!.quantityBaseInternal;const b=await this.repo.getBalance(sale.id,l.saleItemId);if(b.allocated+b.delivered+l.quantityBaseInternal>sold)throw conflict('La carga excede la cantidad vendida');}
 const truck=await this.trucks.findById(trip.truckId);if(!truck)throw notFound('Camión no encontrado');const now=new Date().toISOString();const weights=lines.map(l=>l.estimatedWeightGrams),volumes=lines.map(l=>l.estimatedVolumeMl);const totalWeight=weights.every(v=>v!==undefined)?weights.reduce((a,b)=>a+(b??0),0):undefined;const totalVolume=volumes.every(v=>v!==undefined)?volumes.reduce((a,b)=>a+(b??0),0):undefined;const maxWeight=truck.maxLoadKg===undefined?undefined:truck.maxLoadKg*1000,maxVolume=truck.maxVolumeM3Internal===undefined?undefined:truck.maxVolumeM3Internal*1000;const load:TripLoad={id:existing?.id??randomUUID(),tripId,saleId:sale.id,status:'DRAFT',lines,...(totalWeight===undefined?{}:{totalWeightGrams:totalWeight}),...(totalVolume===undefined?{}:{totalVolumeMl:totalVolume}),...(totalWeight!==undefined&&maxWeight?{weightUtilizationBps:Math.floor(totalWeight*10000/maxWeight)}:{}),...(totalVolume!==undefined&&maxVolume?{volumeUtilizationBps:Math.floor(totalVolume*10000/maxVolume)}:{}),capacityValidation:totalWeight!==undefined&&totalVolume!==undefined?'COMPLETE':'PARTIAL',createdAt:existing?.createdAt??now,createdBy:existing?.createdBy??userId,updatedAt:now,updatedBy:userId};await this.repo.saveDraft(load,existing?.updatedAt);return load;}
 async confirm(tripId:string,userId:string){const old=await this.requireLoad(tripId);if(old.status!=='DRAFT')throw conflict('La carga no está en borrador');const trip=await this.trip(tripId);if(trip.status!=='DRAFT')throw conflict('El viaje no está en borrador');const sale=await this.sales.findById(old.saleId);if(!sale||sale.status!=='CONFIRMED')throw conflict('Venta inválida');const truck=await this.trucks.findById(trip.truckId);if(!truck)throw notFound('Camión no encontrado');if(old.totalWeightGrams!==undefined&&truck.maxLoadKg!==undefined&&old.totalWeightGrams>truck.maxLoadKg*1000)throw conflict('La carga excede el peso máximo');if(old.totalVolumeMl!==undefined&&truck.maxVolumeM3Internal!==undefined&&old.totalVolumeMl>truck.maxVolumeM3Internal*1000)throw conflict('La carga excede el volumen máximo');const now=new Date().toISOString(),load={...old,status:'CONFIRMED' as const,confirmedAt:now,confirmedBy:userId,updatedAt:now,updatedBy:userId};try{await this.repo.confirm(load,new Map(sale.items.map(i=>[i.id,i.quantityBaseInternal])),old.updatedAt);}catch(e){if(e instanceof TripLoadConflictError)throw conflict('La cantidad fue asignada por otra carga');throw e;}return load;}
 async cancel(tripId:string,userId:string){const old=await this.requireLoad(tripId);if(old.status!=='CONFIRMED')throw conflict('La carga no está confirmada');const now=new Date().toISOString(),load={...old,status:'CANCELLED' as const,cancelledAt:now,cancelledBy:userId,updatedAt:now,updatedBy:userId};await this.repo.cancel(load,old.updatedAt);return load;}
 private async requireLoad(id:string){const x=await this.repo.findByTripId(id);if(!x)throw notFound('Carga no encontrada');return x;} private async trip(id:string){const x=await this.trips.findById(id);if(!x)throw notFound('Viaje no encontrado');return x;}
 private async access(id:string,user:string,role:UserRole){const trip=await this.trip(id);if(role==='DRIVER'){let token:string|undefined,own=false;do{const p=await this.drivers.list({limit:100,today:new Date().toISOString().slice(0,10),...(token?{nextToken:token}:{})});own=p.items.some(d=>d.userId===user&&d.id===trip.driverId);token=p.nextToken;}while(token&&!own);if(!own)throw Object.assign(new Error('Acceso no autorizado'),{statusCode:403});}return trip;}
}
const bad=(m:string)=>Object.assign(new Error(m),{statusCode:400});const conflict=(m:string)=>Object.assign(new Error(m),{statusCode:409});const notFound=(m:string)=>Object.assign(new Error(m),{statusCode:404});
