import { randomUUID } from 'node:crypto';
import type { CreateDeliveryRequest, DeliveryEvidenceResponse, DeliveryEvidenceType, DeliveryOutcome, DeliveryReceiptLineResponse, DeliveryReceiptResponse, UpdateDeliveryRequest, UserRole } from '@lcm/contracts';
import { randomUUID as evidenceId } from 'node:crypto';
import type { DriverRepository } from '../../drivers/domain/driver.repository.js';
import type { TripLoadRepository } from '../../trip-loads/domain/trip-load.repository.js';
import type { TripRepository } from '../../trips/domain/trip.repository.js';
import type { TruckRepository } from '../../trucks/domain/truck.repository.js';
import type { DeliveryRepository } from '../domain/delivery.repository.js';
import { DeliveryConflictError } from '../domain/delivery.repository.js';
import type { DeliveryEvidenceStorage } from '../domain/delivery-evidence.storage.js';
export class DeliveriesService {
  constructor(private readonly repo:DeliveryRepository,private readonly trips:TripRepository,private readonly loads:TripLoadRepository,private readonly trucks:TruckRepository,private readonly drivers:DriverRepository,private readonly storage:DeliveryEvidenceStorage,private readonly maxEvidenceBytes=5*1024*1024){}
  async getByTrip(tripId:string,userId:string,role:UserRole){await this.access(tripId,userId,role);return this.repo.findByTripId(tripId);}
  async get(id:string,userId:string,role:UserRole){const d=await this.repo.findById(id);if(!d)throw notFound('Entrega no encontrada');await this.access(d.tripId,userId,role);return d;}
  async list(limit:number,nextToken?:string,saleId?:string,status?:string){return this.repo.list({limit,...(nextToken?{nextToken}:{}),...(saleId?{saleId}:{}),...(status?{status}:{})});}
  async create(tripId:string,input:CreateDeliveryRequest,userId:string,role:UserRole){const trip=await this.access(tripId,userId,role);if(trip.status!=='IN_TRANSIT'||!trip.saleId)throw conflict('La entrega requiere un viaje comercial en tránsito');const load=await this.loads.findByTripId(tripId);if(!load||load.status!=='CONFIRMED')throw conflict('La entrega requiere una carga confirmada');const existing=await this.repo.findByTripId(tripId);if(existing&&existing.status!=='VOIDED')throw conflict('El viaje ya posee un comprobante de entrega');const now=new Date().toISOString(),id=randomUUID();const d:DeliveryReceiptResponse={id,deliveryNumber:await this.repo.nextNumber(Number(now.slice(0,4))),tripId,saleId:trip.saleId,status:'DRAFT',deliveryAddressSnapshot:[trip.destinationAddress,trip.destinationCity].filter(Boolean).join(', '),lines:this.lines(id,load.id,tripId,trip.saleId,load.lines,input.lines,now),createdAt:now,updatedAt:now,createdBy:userId,updatedBy:userId,...clean(input)};await this.repo.create(d);return d;}
  async update(tripId:string,input:UpdateDeliveryRequest,userId:string,role:UserRole){await this.access(tripId,userId,role);const old=await this.requireTripDelivery(tripId);if(old.status!=='DRAFT')throw conflict('Solo una entrega borrador puede modificarse');const load=await this.loads.findByTripId(tripId);if(!load||load.status!=='CONFIRMED')throw conflict('Carga confirmada no encontrada');const now=new Date().toISOString(),d={...old,...clean(input),lines:this.lines(old.id,load.id,old.tripId,old.saleId,load.lines,input.lines,now),updatedAt:now,updatedBy:userId};await this.repo.update(d,old.updatedAt);return d;}
  async confirm(tripId:string,odometerEndKm:number,userId:string,role:UserRole){const trip=await this.access(tripId,userId,role),old=await this.requireTripDelivery(tripId);if(trip.status!=='IN_TRANSIT'||trip.odometerStartKm===undefined||!Number.isSafeInteger(odometerEndKm)||odometerEndKm<trip.odometerStartKm)throw conflict('Odómetro de llegada inválido');if(old.status!=='DRAFT')throw conflict('La entrega no está en borrador');const load=await this.loads.findByTripId(tripId);if(!load||load.status!=='CONFIRMED')throw conflict('Carga confirmada no encontrada');this.validate(old);const truck=await this.trucks.findById(trip.truckId);if(!truck||odometerEndKm<truck.currentOdometerKm)throw conflict('El odómetro no puede disminuir');const now=new Date().toISOString(),total=old.lines.reduce((n,x)=>n+x.deliveredQuantityBaseInternal,0),loaded=old.lines.reduce((n,x)=>n+x.loadedQuantityBaseInternal,0),outcome:DeliveryOutcome=total===0?'FAILED':total===loaded?'FULL':'PARTIAL';const delivery={...old,status:'CONFIRMED' as const,outcome,odometerEndKm,deliveredAt:now,confirmedAt:now,confirmedBy:userId,updatedAt:now,updatedBy:userId};const completedTrip={...trip,status:'DELIVERED' as const,odometerEndKm,distanceKm:odometerEndKm-trip.odometerStartKm,deliveredAt:now,deliveredBy:userId,updatedAt:now,updatedBy:userId};try{await this.repo.confirm(delivery,completedTrip,{...truck,currentOdometerKm:odometerEndKm,updatedAt:now,updatedBy:userId},load,old.updatedAt,trip.updatedAt);}catch(e){if(e instanceof DeliveryConflictError)throw conflict('La entrega fue modificada o confirmada por otra operación');throw e;}return delivery;}
  async void(id:string,reason:string,userId:string){const old=await this.repo.findById(id);if(!old)throw notFound('Entrega no encontrada');if(old.status!=='CONFIRMED'||!reason.trim())throw conflict('La entrega no puede anularse');const now=new Date().toISOString(),d={...old,status:'VOIDED' as const,voidReason:reason.trim(),voidedAt:now,voidedBy:userId,updatedAt:now,updatedBy:userId};await this.repo.void(d,old.updatedAt);return d;}
  async addEvidence(tripId:string,type:DeliveryEvidenceType,fileName:string,mimeType:string,content:Buffer,userId:string,role:UserRole):Promise<DeliveryEvidenceResponse>{await this.access(tripId,userId,role);const delivery=await this.requireTripDelivery(tripId);if(delivery.status!=='DRAFT')throw conflict('Las evidencias solo se agregan al borrador');if(content.length===0||content.length>this.maxEvidenceBytes)throw bad('El archivo debe pesar entre 1 byte y 5 MB');const allowed=type==='SIGNATURE'?['image/jpeg','image/png','image/webp']:['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(mimeType))throw bad('Tipo de archivo no permitido');const existing=await this.repo.evidenceByDelivery(delivery.id);if(existing.length>=5)throw conflict('Máximo de cinco evidencias por entrega');const extension=mimeType==='application/pdf'?'pdf':mimeType.split('/')[1]==='jpeg'?'jpg':mimeType.split('/')[1]??'bin',now=new Date().toISOString(),id=evidenceId(),stored=await this.storage.save(delivery.id,extension,content);const evidence={id,deliveryReceiptId:delivery.id,type,storageKey:stored.storageKey,originalFileName:fileName.slice(0,255),mimeType,sizeBytes:content.length,createdAt:now,createdBy:userId};await this.repo.addEvidence(evidence);return evidence;}
  async evidence(tripId:string,userId:string,role:UserRole){await this.access(tripId,userId,role);const d=await this.requireTripDelivery(tripId);return(await this.repo.evidenceByDelivery(d.id)).map(({storageKey:_storageKey,...x})=>x);}
  async evidenceFile(id:string,userId:string,role:UserRole){const e=await this.repo.findEvidence(id);if(!e)throw notFound('Evidencia no encontrada');const d=await this.repo.findById(e.deliveryReceiptId);if(!d)throw notFound('Entrega no encontrada');await this.access(d.tripId,userId,role);return{path:await this.storage.resolve(e.storageKey),mimeType:e.mimeType,fileName:e.originalFileName};}
  private lines(deliveryId:string,loadId:string,tripId:string,saleId:string,loadLines:readonly {id:string;saleItemId:string;productId:string;productCode:string;productName:string;baseUnit:string;quantityScale:number;quantityBaseInternal:number}[],inputs:CreateDeliveryRequest['lines'],now:string):DeliveryReceiptLineResponse[]{return loadLines.map(line=>{const input=inputs?.find(x=>x.tripLoadLineId===line.id);const delivered=input?.deliveredQuantityBaseInternal??line.quantityBaseInternal;if(!Number.isSafeInteger(delivered)||delivered<0||delivered>line.quantityBaseInternal)throw bad('Cantidad entregada inválida');const incident=input?.incidentType??'NONE',notes=input?.incidentNotes?.trim();if(delivered<line.quantityBaseInternal&&(incident==='NONE'||!notes))throw bad('La diferencia requiere motivo y observación');if(delivered===line.quantityBaseInternal&&incident!=='NONE')throw bad('Una entrega completa no requiere incidencia');return{id:randomUUID(),deliveryReceiptId:deliveryId,tripId,tripLoadId:loadId,tripLoadLineId:line.id,saleId,saleItemId:line.saleItemId,productId:line.productId,productSnapshot:{code:line.productCode,name:line.productName,baseUnit:line.baseUnit,quantityScale:line.quantityScale},loadedQuantityBaseInternal:line.quantityBaseInternal,deliveredQuantityBaseInternal:delivered,undeliveredQuantityBaseInternal:line.quantityBaseInternal-delivered,incidentType:incident,...(notes?{incidentNotes:notes}:{}),createdAt:now,updatedAt:now};});}
  private validate(d:DeliveryReceiptResponse){const delivered=d.lines.reduce((n,x)=>n+x.deliveredQuantityBaseInternal,0);if(delivered>0&&!d.receiverName?.trim())throw bad('Nombre del receptor requerido');for(const x of d.lines)if(x.deliveredQuantityBaseInternal<x.loadedQuantityBaseInternal&&(x.incidentType==='NONE'||!x.incidentNotes?.trim()))throw bad('Toda diferencia requiere incidencia');}
  private async requireTripDelivery(id:string){const d=await this.repo.findByTripId(id);if(!d)throw notFound('Entrega no encontrada');return d;}
  private async access(id:string,user:string,role:UserRole){const trip=await this.trips.findById(id);if(!trip)throw notFound('Viaje no encontrado');if(role==='DRIVER'){let token:string|undefined,own=false;do{const p=await this.drivers.list({limit:100,today:new Date().toISOString().slice(0,10),...(token?{nextToken:token}:{})});own=p.items.some(x=>x.userId===user&&x.id===trip.driverId);token=p.nextToken;}while(token&&!own);if(!own)throw forbidden();}return trip;}
}
function clean(i:CreateDeliveryRequest){return{...(i.receiverName?.trim()?{receiverName:i.receiverName.trim()}:{}),...(i.receiverDocument?.trim()?{receiverDocument:i.receiverDocument.trim()}:{}),...(i.receiverPhone?.trim()?{receiverPhone:i.receiverPhone.trim()}:{}),...(i.generalNotes?.trim()?{generalNotes:i.generalNotes.trim()}:{})};}
const bad=(m:string)=>Object.assign(new Error(m),{statusCode:400});const conflict=(m:string)=>Object.assign(new Error(m),{statusCode:409});const notFound=(m:string)=>Object.assign(new Error(m),{statusCode:404});const forbidden=()=>Object.assign(new Error('Acceso no autorizado'),{statusCode:403});
