import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import type { DeliveryEvidenceResponse, DeliveryIncidentType, DeliveryOutcome, DeliveryReceiptResponse, TripResponse } from '@lcm/contracts';
import { finalize, forkJoin, of, switchMap } from 'rxjs';
import { PermissionService } from '../../core/permissions/permission.service';
import { displayToInternal, internalToDisplay } from '../../shared/quantity';
import { DeliverySignaturePadComponent } from './delivery-signature-pad.component';
import { DeliveryStatusBadgeComponent } from './delivery-status-badge.component';
import { TripsApiService } from './trips-api.service';

interface PendingEvidence { file:File; url?:string; state:'PENDING'|'UPLOADING'|'ERROR'; }
@Component({selector:'lcm-delivery-page',standalone:true,imports:[FormsModule,RouterLink,DeliveryStatusBadgeComponent,DeliverySignaturePadComponent],templateUrl:'./delivery-page.component.html',styleUrl:'./delivery-page.component.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class DeliveryPageComponent {
  private readonly api=inject(TripsApiService);private readonly route=inject(ActivatedRoute);private readonly destroyRef=inject(DestroyRef);private readonly permissions=inject(PermissionService);
  readonly trip=signal<TripResponse|null>(null);readonly delivery=signal<DeliveryReceiptResponse|null>(null);readonly evidence=signal<readonly DeliveryEvidenceResponse[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly error=signal<string|null>(null);readonly feedback=signal<string|null>(null);readonly confirmOpen=signal(false);readonly attempted=signal(false);readonly pending=signal<PendingEvidence|null>(null);readonly signatureBlob=signal<Blob|null>(null);
  readonly canCreate=this.permissions.has('deliveries.create');readonly canConfirm=this.permissions.has('deliveries.confirm');readonly canEvidence=this.permissions.has('delivery_evidence.create');
  readonly canReadEvidence=this.permissions.has('delivery_evidence.read');readonly downloading=signal(false);
  fileSize(bytes:number){if(bytes<1024)return `${this.format(bytes)} bytes`;if(bytes<1048576)return `${this.format(bytes/1024)} KB`;return `${this.format(bytes/1048576)} MB`;}
  downloadEvidence(file:DeliveryEvidenceResponse){if(!this.canReadEvidence||this.downloading())return;this.downloading.set(true);this.api.evidenceFile(file.id).pipe(finalize(()=>this.downloading.set(false))).subscribe({next:blob=>{const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=file.originalFileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);},error:()=>this.error.set('No se pudo descargar la evidencia. Intentá nuevamente.')});}
  readonly quantities:Record<string,number>={};readonly incidents:Record<string,DeliveryIncidentType>={};readonly incidentNotes:Record<string,string>={};receiverName='';receiverDocument='';receiverPhone='';generalNotes='';odometerEndKm=0;
  constructor(){this.load();this.destroyRef.onDestroy(()=>{const url=this.pending()?.url;if(url)URL.revokeObjectURL(url);});}
  load(){const id=this.route.snapshot.paramMap.get('id');if(!id)return;this.loading.set(true);this.error.set(null);forkJoin({trip:this.api.get(id),delivery:this.api.getDelivery(id)}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:({trip,delivery})=>{this.trip.set(trip);this.delivery.set(delivery);this.odometerEndKm=delivery?.odometerEndKm??trip.odometerStartKm??0;if(delivery){this.hydrate(delivery);this.loadEvidence(id);}},error:()=>this.error.set('No pudimos cargar la entrega.')});}
  create(){const trip=this.trip();if(!trip)return;this.saving.set(true);this.api.createDelivery(trip.id,{}).pipe(finalize(()=>this.saving.set(false))).subscribe({next:d=>{this.delivery.set(d);this.hydrate(d);},error:()=>this.error.set('No se pudo iniciar la entrega.')});}
  allDelivered(){const d=this.delivery();if(!d)return;for(const line of d.lines){this.quantities[line.tripLoadLineId]=this.display(line.loadedQuantityBaseInternal,line.productSnapshot.quantityScale);this.incidents[line.tripLoadLineId]='NONE';this.incidentNotes[line.tripLoadLineId]='';}this.feedback.set('Todas las cantidades se marcaron como entregadas. Revisá los datos antes de confirmar.');}
  difference(line:DeliveryReceiptResponse['lines'][number]){return Math.max(0,this.display(line.loadedQuantityBaseInternal,line.productSnapshot.quantityScale)-Number(this.quantities[line.tripLoadLineId]??0));}
  lineError(line:DeliveryReceiptResponse['lines'][number]){const value=Number(this.quantities[line.tripLoadLineId]);const max=this.display(line.loadedQuantityBaseInternal,line.productSnapshot.quantityScale);if(!Number.isFinite(value)||value<0)return 'Ingresá una cantidad válida.';if(value>max)return `La cantidad entregada no puede superar las ${this.format(max)} ${line.productSnapshot.baseUnit} cargadas.`;if(value<max&&(!this.incidents[line.tripLoadLineId]||this.incidents[line.tripLoadLineId]==='NONE'))return 'Seleccioná el motivo de la diferencia.';if(value<max&&!this.incidentNotes[line.tripLoadLineId]?.trim())return 'Explicá brevemente la diferencia.';return null;}
  formErrors(){const d=this.delivery();if(!d)return 1;return d.lines.filter(x=>this.lineError(x)).length+(!this.receiverName.trim()&&this.totalDelivered()>0?1:0)+(this.odometerEndKm<(this.trip()?.odometerStartKm??0)?1:0);}
  saveDraft(){this.attempted.set(true);if(this.delivery()?.lines.some(x=>this.lineError(x)))return this.showErrors();this.persist('Borrador guardado correctamente.');}
  requestConfirm(){this.attempted.set(true);if(this.formErrors()){this.showErrors();return;}this.confirmOpen.set(true);}
  confirm(){const trip=this.trip();if(!trip)return;this.confirmOpen.set(false);this.saving.set(true);this.api.updateDelivery(trip.id,this.input()).pipe(switchMap(()=>this.uploadPending(trip.id)),switchMap(()=>this.api.confirmDelivery(trip.id,Number(this.odometerEndKm))),finalize(()=>this.saving.set(false))).subscribe({next:d=>{this.delivery.set(d);this.feedback.set('Entrega confirmada correctamente.');this.loadEvidence(trip.id);},error:()=>this.error.set('No se pudo confirmar la entrega. Revisá los datos e intentá nuevamente.')});}
  chooseEvidence(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const old=this.pending()?.url;if(old)URL.revokeObjectURL(old);this.pending.set({file,url:file.type.startsWith('image/')?URL.createObjectURL(file):undefined,state:'PENDING'});}
  removePending(){const url=this.pending()?.url;if(url)URL.revokeObjectURL(url);this.pending.set(null);}
  retryEvidence(){const trip=this.trip();if(trip)this.uploadPending(trip.id).subscribe({next:()=>this.feedback.set('Evidencia cargada correctamente.'),error:()=>undefined});}
  signatureChanged(blob:Blob){this.signatureBlob.set(blob);}
  scrollTo(id:string){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});}
  incidentLabel(type:DeliveryIncidentType){const labels:Record<DeliveryIncidentType,string>={NONE:'Sin incidente',SHORTAGE:'Faltante',DAMAGED:'Dañado',REJECTED:'Rechazado',CUSTOMER_ABSENT:'Cliente ausente',ACCESS_PROBLEM:'Problema de acceso',OTHER:'Otro'};return labels[type];}
  display(value:number,scale:number){return internalToDisplay(value,scale);}format(value:number){return new Intl.NumberFormat('es-PY',{maximumFractionDigits:3}).format(value);}
  totalDelivered(){return this.delivery()?.lines.reduce((n,x)=>n+Number(this.quantities[x.tripLoadLineId]??0),0)??0;}completeCount(){return this.delivery()?.lines.filter(x=>this.difference(x)===0).length??0;}differenceCount(){return this.delivery()?.lines.filter(x=>this.difference(x)>0).length??0;}
  hasSignature(){return this.evidence().some(item=>item.type==='SIGNATURE');}
  outcome():DeliveryOutcome|undefined{const d=this.delivery();if(!d)return undefined;const delivered=this.totalDelivered();if(delivered===0)return'FAILED';return this.differenceCount()?'PARTIAL':'FULL';}
  private persist(message:string){const trip=this.trip();if(!trip)return;this.saving.set(true);this.api.updateDelivery(trip.id,this.input()).pipe(switchMap(d=>{this.delivery.set(d);return this.uploadPending(trip.id);}),finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.feedback.set(message);this.loadEvidence(trip.id);},error:()=>this.error.set('No se pudo guardar el borrador.')});}
  private uploadPending(tripId:string){const item=this.pending();const signature=this.signatureBlob();const uploads=[];if(item){this.pending.set({...item,state:'UPLOADING'});uploads.push(this.api.uploadEvidence(tripId,item.file,item.file.type==='application/pdf'?'DOCUMENT':'PHOTO'));}if(signature)uploads.push(this.api.uploadEvidence(tripId,new File([signature],'firma.png',{type:'image/png'}),'SIGNATURE'));if(!uploads.length)return of([]);return forkJoin(uploads).pipe(finalize(()=>{}),switchMap(result=>{this.removePending();this.signatureBlob.set(null);return of(result);}),finalize(()=>{const current=this.pending();if(current?.state==='UPLOADING')this.pending.set({...current,state:'ERROR'});}));}
  private input(){const d=this.delivery()!;return{receiverName:this.receiverName,receiverDocument:this.receiverDocument,receiverPhone:this.receiverPhone,generalNotes:this.generalNotes,lines:d.lines.map(x=>({tripLoadLineId:x.tripLoadLineId,deliveredQuantityBaseInternal:displayToInternal(Number(this.quantities[x.tripLoadLineId]),x.productSnapshot.quantityScale),incidentType:this.difference(x)>0?(this.incidents[x.tripLoadLineId]??'NONE'):'NONE',...(this.difference(x)>0&&this.incidentNotes[x.tripLoadLineId]?.trim()?{incidentNotes:this.incidentNotes[x.tripLoadLineId].trim()}: {})}))};}
  private hydrate(d:DeliveryReceiptResponse){this.receiverName=d.receiverName??'';this.receiverDocument=d.receiverDocument??'';this.receiverPhone=d.receiverPhone??'';this.generalNotes=d.generalNotes??'';for(const x of d.lines){this.quantities[x.tripLoadLineId]=this.display(x.deliveredQuantityBaseInternal,x.productSnapshot.quantityScale);this.incidents[x.tripLoadLineId]=x.incidentType;this.incidentNotes[x.tripLoadLineId]=x.incidentNotes??'';}}
  private loadEvidence(id:string){this.api.evidence(id).subscribe({next:x=>this.evidence.set(x),error:()=>this.error.set('No se pudieron cargar las evidencias.')});}
  private showErrors(){this.error.set(`No se puede confirmar la entrega. Revisá ${this.formErrors()} campos marcados.`);setTimeout(()=>document.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());}
}
