import { TransactionCanceledException } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, QueryCommand, TransactWriteCommand } from '@aws-sdk/lib-dynamodb';
import type { InventoryMovement } from '../../inventory/domain/inventory.js';
import type { DynamoDbInventoryRepository } from '../../inventory/infrastructure/dynamodb-inventory.repository.js';
import type { Sale } from '../domain/sale.js';
import { SaleConflictError, type SaleListOptions, type SalePage, type SaleRepository } from '../domain/sale.repository.js';
import type { SaleFinancialPosting } from '../domain/sale.repository.js';
import type { DynamoDbCashRepository } from '../../cash/infrastructure/dynamodb-cash.repository.js';
export class DynamoDbSaleRepository implements SaleRepository {
  constructor(private readonly client:DynamoDBDocumentClient,private readonly tableName:string,private readonly inventory:DynamoDbInventoryRepository,private readonly cash?:DynamoDbCashRepository){}
  async findById(id:string){const r=await this.client.send(new GetCommand({TableName:this.tableName,Key:{pk:`SALE#${id}`},ConsistentRead:true}));return r.Item?r.Item['data'] as Sale:null;}
  async list(o:SaleListOptions):Promise<SalePage>{let key:Record<string,unknown>|undefined;if(o.nextToken){try{key=JSON.parse(Buffer.from(o.nextToken,'base64url').toString()) as Record<string,unknown>;}catch{throw Object.assign(new Error('Cursor inválido'),{statusCode:400});}}const names:Record<string,string>={};const values:Record<string,unknown>={':datePk':'SALE'};const filters:string[]=[];for(const field of ['status','customerId','paymentMethod'] as const){if(o[field]){names[`#${field}`]=field;values[`:${field}`]=o[field];filters.push(`#${field} = :${field}`);}}if(o.userId){names['#createdBy']='createdBy';values[':createdBy']=o.userId;filters.push('#createdBy = :createdBy');}if(o.search){names['#search']='searchText';values[':search']=o.search.toLocaleLowerCase('es');filters.push('contains(#search,:search)');}let condition='datePk = :datePk';if(o.dateFrom&&o.dateTo){values[':from']=o.dateFrom;values[':to']=`${o.dateTo}\uffff`;condition+=' AND dateSk BETWEEN :from AND :to';}else if(o.dateFrom){values[':from']=o.dateFrom;condition+=' AND dateSk >= :from';}else if(o.dateTo){values[':to']=`${o.dateTo}\uffff`;condition+=' AND dateSk <= :to';}const r=await this.client.send(new QueryCommand({TableName:this.tableName,IndexName:'SaleDateIndex',KeyConditionExpression:condition,ExpressionAttributeValues:values,...(Object.keys(names).length?{ExpressionAttributeNames:names}:{}),...(filters.length?{FilterExpression:filters.join(' AND ')}:{}),Limit:o.limit,ScanIndexForward:false,...(key?{ExclusiveStartKey:key}:{})}));return{items:(r.Items??[]).map(i=>i['data'] as Sale),...(r.LastEvaluatedKey?{nextToken:Buffer.from(JSON.stringify(r.LastEvaluatedKey)).toString('base64url')}:{})};}
  async create(sale:Sale){try{await this.client.send(new TransactWriteCommand({TransactItems:[{Put:{TableName:this.tableName,Item:record(sale),ConditionExpression:'attribute_not_exists(pk)'}},{Put:{TableName:this.tableName,Item:{pk:`SALE_NUMBER#${sale.saleNumber}`,entityType:'NUMBER',saleId:sale.id},ConditionExpression:'attribute_not_exists(pk)'}}]}));}catch(e){if(e instanceof TransactionCanceledException)throw new SaleConflictError('NUMBER');throw e;}}
  async replace(sale:Sale,expected:string){await this.write(sale,[],expected);}
  async confirm(sale:Sale,m:readonly InventoryMovement[],expected:string,f?:SaleFinancialPosting){await this.write(sale,m,expected,f);}
  async void(sale:Sale,m:readonly InventoryMovement[],expected:string,f?:SaleFinancialPosting){await this.write(sale,m,expected,f);}
  private async write(sale:Sale,movements:readonly InventoryMovement[],expected:string,financial?:SaleFinancialPosting){try{await this.client.send(new TransactWriteCommand({TransactItems:[{Put:{TableName:this.tableName,Item:record(sale),ConditionExpression:'#updatedAt = :expected',ExpressionAttributeNames:{'#updatedAt':'updatedAt'},ExpressionAttributeValues:{':expected':expected}}},...this.inventory.transactionItems(movements),...(financial&&this.cash?this.cash.transactionItems(financial.movement):[])]}));}catch(e){if(e instanceof TransactionCanceledException)throw new SaleConflictError(movements.some(m=>m.type==='SALE')?'STOCK':'CONCURRENT');throw e;}}
}
function record(s:Sale){return{pk:`SALE#${s.id}`,entityType:'SALE',datePk:'SALE',dateSk:`${s.saleDate}#${s.createdAt}#${s.id}`,status:s.status,customerId:s.customerId,paymentMethod:s.paymentMethod,saleDate:s.saleDate,createdBy:s.createdBy,updatedAt:s.updatedAt,searchText:`${s.saleNumber} ${s.customerSnapshot?.displayName??'consumidor final'}`.toLocaleLowerCase('es'),data:s};}
