import { PURCHASE_RECEIPT_STATUSES, hasPermission, type CreatePurchaseReceiptRequest, type PurchaseReceiptStatus, type UpdatePurchaseReceiptRequest } from '@lcm/contracts';
import type { FastifyInstance } from 'fastify';
import type { AuthService } from '../../auth/application/auth.service.js';
import { authenticatedUser, requirePermission } from '../../auth/http/authorization.js';
import type { ReceivingService } from '../application/receiving.service.js';
interface Options { readonly authService: AuthService; readonly service: ReceivingService; }
interface IdParams { readonly id: string; } interface ReceiptQuery { readonly pageSize?: number; readonly nextToken?: string; readonly search?: string; readonly purchaseId?: string; readonly supplierId?: string; readonly status?: PurchaseReceiptStatus; readonly dateFrom?: string; readonly dateTo?: string; }
const id = { type: 'string', format: 'uuid' } as const; const date = { type: 'string', format: 'date' } as const; const params = { type: 'object', required: ['id'], properties: { id } } as const;
const line = { type: 'object', additionalProperties: false, required: ['purchaseItemId', 'receivedQuantity'], properties: { purchaseItemId: id, receivedQuantity: { type: 'string', pattern: '^\\d+(?:[.,]\\d+)?$', maxLength: 30 }, notes: { type: 'string', maxLength: 500 } } } as const;
const fields = { receiptDate: date, deliveryDocumentNumber: { type: 'string', maxLength: 100 }, notes: { type: 'string', maxLength: 1500 }, lines: { type: 'array', minItems: 1, maxItems: 5, items: line } } as const;
export async function receivingRoutes(app: FastifyInstance, options: Options): Promise<void> {
  app.get<{ Querystring: ReceiptQuery }>('/', { preHandler: requirePermission(options.authService, 'receipts.read'), schema: { querystring: { type: 'object', additionalProperties: false, properties: { pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 25 }, nextToken: { type: 'string', maxLength: 1000 }, search: { type: 'string', maxLength: 180 }, purchaseId: id, supplierId: id, status: { type: 'string', enum: [...PURCHASE_RECEIPT_STATUSES] }, dateFrom: date, dateTo: date } } } }, async (request) => { const actor = authenticatedUser(request); return options.service.listReceipts({ limit: request.query.pageSize ?? 25, ...defined(request.query) }, hasPermission(actor.role, 'lots.costs.read')); });
  app.get<{ Params: IdParams }>('/:id', { preHandler: requirePermission(options.authService, 'receipts.read'), schema: { params } }, async (request) => { const actor = authenticatedUser(request); return options.service.getReceipt(request.params.id, hasPermission(actor.role, 'lots.costs.read')); });
  app.post<{ Body: CreatePurchaseReceiptRequest }>('/', { preHandler: requirePermission(options.authService, 'receipts.create'), schema: { body: { type: 'object', additionalProperties: false, required: ['purchaseId', 'receiptDate', 'lines'], properties: { purchaseId: id, ...fields } } } }, async (request, reply) => { const actor = authenticatedUser(request); return reply.status(201).send(await options.service.create(request.body, actor.userId, hasPermission(actor.role, 'lots.costs.read'))); });
  app.patch<{ Params: IdParams; Body: UpdatePurchaseReceiptRequest }>('/:id', { preHandler: requirePermission(options.authService, 'receipts.update'), schema: { params, body: { type: 'object', additionalProperties: false, minProperties: 1, properties: fields } } }, async (request) => { const actor = authenticatedUser(request); return options.service.update(request.params.id, request.body, actor.userId, hasPermission(actor.role, 'lots.costs.read')); });
  app.post<{ Params: IdParams }>('/:id/confirm', { preHandler: requirePermission(options.authService, 'receipts.confirm'), schema: { params } }, async (request) => { const actor = authenticatedUser(request); return options.service.confirm(request.params.id, actor.userId, hasPermission(actor.role, 'lots.costs.read')); });
  app.post<{ Params: IdParams }>('/:id/cancel', { preHandler: requirePermission(options.authService, 'receipts.cancel'), schema: { params } }, async (request) => { const actor = authenticatedUser(request); return options.service.cancel(request.params.id, actor.userId, hasPermission(actor.role, 'lots.costs.read')); });
}
function defined(value: ReceiptQuery): Omit<ReceiptQuery, 'pageSize'> { const { pageSize: _page, ...rest } = value; void _page; return rest; }
