import { TransactionCanceledException } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, ScanCommand, TransactWriteCommand, type TransactWriteCommandInput } from '@aws-sdk/lib-dynamodb';
import type { TripLoadRepository } from '../domain/trip-load.repository.js';
import { TripLoadConflictError } from '../domain/trip-load.repository.js';
import { maintainBalances } from './balance-maintenance.js';
import type { TripLoad } from '../domain/trip-load.js';
export class DynamoDbTripLoadRepository implements TripLoadRepository {
 constructor(private readonly c:DynamoDBDocumentClient,private readonly table:string,private readonly deliveriesTable?:string){}
 async findByTripId(id:string){const r=await this.c.send(new GetCommand({TableName:this.table,Key:{pk:`LOAD#${id}`},ConsistentRead:true}));return r.Item?.['data'] as TripLoad??null;}
 async saveDraft(load:TripLoad,expected?:string){await this.write([{Put:{TableName:this.table,Item:item(load),ConditionExpression:expected?'updatedAt = :e':'attribute_not_exists(pk)',...(expected?{ExpressionAttributeValues:{':e':expected}}:{})}}]);}
 async confirm(load:TripLoad,sold:ReadonlyMap<string,number>,expected:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(load),ConditionExpression:'updatedAt = :e AND #data.#status = :draft',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':expected,':draft':'DRAFT'}}}];for(const l of load.lines){const balance=await this.getBalance(load.saleId,l.saleItemId);const remaining=(sold.get(l.saleItemId)??0)-balance.delivered-l.quantityBaseInternal;if(remaining<0)throw new TripLoadConflictError();tx.push({Update:{TableName:this.table,Key:{pk:`BALANCE#${load.saleId}#${l.saleItemId}`},UpdateExpression:'SET entityType=:type, saleId=:sale, saleItemId=:item, soldQuantityBaseInternal=:sold ADD allocatedQuantityBaseInternal :q, #version :one',ConditionExpression:'attribute_not_exists(pk) OR (allocatedQuantityBaseInternal <= :remaining AND (deliveredQuantityBaseInternal = :delivered OR (attribute_not_exists(deliveredQuantityBaseInternal) AND :delivered = :zero)))',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':one':1,':type':'DELIVERY_BALANCE',':sale':load.saleId,':item':l.saleItemId,':sold':sold.get(l.saleItemId)??0,':q':l.quantityBaseInternal,':remaining':remaining,':delivered':balance.delivered,':zero':0}}});}await this.write(tx);}
 async cancel(load:TripLoad,expected:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(load),ConditionExpression:'updatedAt = :e AND #data.#status = :confirmed',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':expected,':confirmed':'CONFIRMED'}}}];for(const l of load.lines)tx.push({Update:{TableName:this.table,Key:{pk:`BALANCE#${load.saleId}#${l.saleItemId}`},UpdateExpression:'ADD allocatedQuantityBaseInternal :q, #version :one',ConditionExpression:'allocatedQuantityBaseInternal >= :positive',ExpressionAttributeNames:{'#version':'version'},ExpressionAttributeValues:{':one':1,':q':-l.quantityBaseInternal,':positive':l.quantityBaseInternal}}});await this.write(tx);}
 async allocatedForSale(saleId:string,exclude?:string){const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e AND saleId=:s',ExpressionAttributeValues:{':e':'TRIP_LOAD',':s':saleId}}));const out=new Map<string,number>();for(const x of (r.Items??[]).map(i=>i['data'] as TripLoad))if(x.status==='CONFIRMED'&&x.tripId!==exclude)for(const l of x.lines)out.set(l.saleItemId,(out.get(l.saleItemId)??0)+l.quantityBaseInternal);return out;}
 async getBalance(saleId:string,saleItemId:string){const r=await this.c.send(new GetCommand({TableName:this.table,Key:{pk:`BALANCE#${saleId}#${saleItemId}`},ConsistentRead:true}));return{allocated:Number(r.Item?.['allocatedQuantityBaseInternal']??0),delivered:Number(r.Item?.['deliveredQuantityBaseInternal']??0)};}
 async all(){const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e',ExpressionAttributeValues:{':e':'TRIP_LOAD'}}));return(r.Items??[]).map(i=>i['data'] as TripLoad);}
 async rebuildBalances(){if(!this.deliveriesTable)throw new Error('La reconstrucción requiere la tabla de entregas');await maintainBalances(this.c,this.table,this.deliveriesTable,true);}
 async verifyBalances(){if(this.deliveriesTable)return maintainBalances(this.c,this.table,this.deliveriesTable,false);const expected=new Map<string,number>();for(const load of await this.all())if(load.status==='CONFIRMED')for(const line of load.lines){const key=`${load.saleId}#${line.saleItemId}`;expected.set(key,(expected.get(key)??0)+line.quantityBaseInternal);}const actual=new Map((await this.scanBalances()).map(x=>[`${String(x['saleId'])}#${String(x['saleItemId'])}`,Number(x['allocatedQuantityBaseInternal'])]));const issues:string[]=[];for(const key of new Set([...expected.keys(),...actual.keys()]))if((expected.get(key)??0)!==(actual.get(key)??0))issues.push(`${key}: histórico=${expected.get(key)??0}, proyección=${actual.get(key)??0}`);return issues;}
 private async scanBalances(){const out:Record<string,unknown>[]=[];let key:Record<string,unknown>|undefined;do{const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e',ExpressionAttributeValues:{':e':'DELIVERY_BALANCE'},...(key?{ExclusiveStartKey:key}:{})}));out.push(...(r.Items??[]));key=r.LastEvaluatedKey;}while(key);return out;}
 private async write(tx:NonNullable<TransactWriteCommandInput['TransactItems']>){try{await this.c.send(new TransactWriteCommand({TransactItems:tx}));}catch(e){if(e instanceof TransactionCanceledException)throw new TripLoadConflictError();throw e;}}
}
function item(load:TripLoad){return{pk:`LOAD#${load.tripId}`,entityType:'TRIP_LOAD',saleId:load.saleId,updatedAt:load.updatedAt,data:load};}
