import { TransactionCanceledException } from '@aws-sdk/client-dynamodb';
import { BatchWriteCommand, DynamoDBDocumentClient, GetCommand, ScanCommand, TransactWriteCommand, type TransactWriteCommandInput } from '@aws-sdk/lib-dynamodb';
import type { TripLoadRepository } from '../domain/trip-load.repository.js';
import { TripLoadConflictError } from '../domain/trip-load.repository.js';
import type { TripLoad } from '../domain/trip-load.js';
export class DynamoDbTripLoadRepository implements TripLoadRepository {
 constructor(private readonly c:DynamoDBDocumentClient,private readonly table:string){}
 async findByTripId(id:string){const r=await this.c.send(new GetCommand({TableName:this.table,Key:{pk:`LOAD#${id}`},ConsistentRead:true}));return r.Item?.['data'] as TripLoad??null;}
 async saveDraft(load:TripLoad,expected?:string){await this.write([{Put:{TableName:this.table,Item:item(load),ConditionExpression:expected?'updatedAt = :e':'attribute_not_exists(pk)',...(expected?{ExpressionAttributeValues:{':e':expected}}:{})}}]);}
 async confirm(load:TripLoad,sold:ReadonlyMap<string,number>,expected:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(load),ConditionExpression:'updatedAt = :e AND #data.#status = :draft',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':expected,':draft':'DRAFT'}}}];for(const l of load.lines)tx.push({Update:{TableName:this.table,Key:{pk:`BALANCE#${load.saleId}#${l.saleItemId}`},UpdateExpression:'SET entityType=:type, saleId=:sale, saleItemId=:item, soldQuantityBaseInternal=:sold ADD allocatedQuantityBaseInternal :q',ConditionExpression:'attribute_not_exists(pk) OR allocatedQuantityBaseInternal + :q <= :sold',ExpressionAttributeValues:{':type':'DELIVERY_BALANCE',':sale':load.saleId,':item':l.saleItemId,':sold':sold.get(l.saleItemId)??0,':q':l.quantityBaseInternal}}});await this.write(tx);}
 async cancel(load:TripLoad,expected:string){const tx:NonNullable<TransactWriteCommandInput['TransactItems']>=[{Put:{TableName:this.table,Item:item(load),ConditionExpression:'updatedAt = :e AND #data.#status = :confirmed',ExpressionAttributeNames:{'#data':'data','#status':'status'},ExpressionAttributeValues:{':e':expected,':confirmed':'CONFIRMED'}}}];for(const l of load.lines)tx.push({Update:{TableName:this.table,Key:{pk:`BALANCE#${load.saleId}#${l.saleItemId}`},UpdateExpression:'ADD allocatedQuantityBaseInternal :q',ConditionExpression:'allocatedQuantityBaseInternal >= :positive',ExpressionAttributeValues:{':q':-l.quantityBaseInternal,':positive':l.quantityBaseInternal}}});await this.write(tx);}
 async allocatedForSale(saleId:string,exclude?:string){const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e AND saleId=:s',ExpressionAttributeValues:{':e':'TRIP_LOAD',':s':saleId}}));const out=new Map<string,number>();for(const x of (r.Items??[]).map(i=>i['data'] as TripLoad))if(x.status==='CONFIRMED'&&x.tripId!==exclude)for(const l of x.lines)out.set(l.saleItemId,(out.get(l.saleItemId)??0)+l.quantityBaseInternal);return out;}
 async all(){const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e',ExpressionAttributeValues:{':e':'TRIP_LOAD'}}));return(r.Items??[]).map(i=>i['data'] as TripLoad);}
 async rebuildBalances(){const existing=await this.scanBalances();for(let i=0;i<existing.length;i+=25)await this.c.send(new BatchWriteCommand({RequestItems:{[this.table]:existing.slice(i,i+25).map(x=>({DeleteRequest:{Key:{pk:x['pk']}}}))}}));const totals=new Map<string,{saleId:string;saleItemId:string;quantity:number}>();for(const load of await this.all())if(load.status==='CONFIRMED')for(const line of load.lines){const key=`${load.saleId}#${line.saleItemId}`,old=totals.get(key);totals.set(key,{saleId:load.saleId,saleItemId:line.saleItemId,quantity:(old?.quantity??0)+line.quantityBaseInternal});}const values=[...totals.values()];for(let i=0;i<values.length;i+=25)await this.c.send(new BatchWriteCommand({RequestItems:{[this.table]:values.slice(i,i+25).map(x=>({PutRequest:{Item:{pk:`BALANCE#${x.saleId}#${x.saleItemId}`,entityType:'DELIVERY_BALANCE',saleId:x.saleId,saleItemId:x.saleItemId,allocatedQuantityBaseInternal:x.quantity}}}))}}));}
 async verifyBalances(){const expected=new Map<string,number>();for(const load of await this.all())if(load.status==='CONFIRMED')for(const line of load.lines){const key=`${load.saleId}#${line.saleItemId}`;expected.set(key,(expected.get(key)??0)+line.quantityBaseInternal);}const actual=new Map((await this.scanBalances()).map(x=>[`${String(x['saleId'])}#${String(x['saleItemId'])}`,Number(x['allocatedQuantityBaseInternal'])]));const issues:string[]=[];for(const key of new Set([...expected.keys(),...actual.keys()]))if((expected.get(key)??0)!==(actual.get(key)??0))issues.push(`${key}: histórico=${expected.get(key)??0}, proyección=${actual.get(key)??0}`);return issues;}
 private async scanBalances(){const out:Record<string,unknown>[]=[];let key:Record<string,unknown>|undefined;do{const r=await this.c.send(new ScanCommand({TableName:this.table,ConsistentRead:true,FilterExpression:'entityType=:e',ExpressionAttributeValues:{':e':'DELIVERY_BALANCE'},...(key?{ExclusiveStartKey:key}:{})}));out.push(...(r.Items??[]));key=r.LastEvaluatedKey;}while(key);return out;}
 private async write(tx:NonNullable<TransactWriteCommandInput['TransactItems']>){try{await this.c.send(new TransactWriteCommand({TransactItems:tx}));}catch(e){if(e instanceof TransactionCanceledException)throw new TripLoadConflictError();throw e;}}
}
function item(load:TripLoad){return{pk:`LOAD#${load.tripId}`,entityType:'TRIP_LOAD',saleId:load.saleId,updatedAt:load.updatedAt,data:load};}
