import { SALE_DELIVERY_TYPES, SALE_PAYMENT_METHODS, SALE_STATUSES, hasPermission, type CreateSaleRequest, type SalePaymentMethod, type SaleStatus, type UpdateSaleRequest, type VoidSaleRequest } from '@lcm/contracts';
import type { FastifyInstance } from 'fastify';
import type { AuthService } from '../../auth/application/auth.service.js';
import { authenticatedUser, requirePermission } from '../../auth/http/authorization.js';
import type { SalesService } from '../application/sales.service.js';
import type { FifoCostingService } from '../../costing/application/fifo-costing.service.js';
interface Options{readonly authService:AuthService;readonly service:SalesService;readonly costing:FifoCostingService} interface Id{readonly id:string}
const uuid={type:'string',format:'uuid'} as const;const params={type:'object',required:['id'],properties:{id:uuid}} as const;
const item={type:'object',additionalProperties:false,required:['productId','presentationId','quantity'],properties:{productId:uuid,presentationId:uuid,quantity:{type:'string',pattern:'^(?:0|[1-9]\\d*)(?:\\.\\d{1,6})?$'},notes:{type:'string',maxLength:500}}} as const;
const fields={customerId:uuid,saleDate:{type:'string',format:'date'},items:{type:'array',minItems:1,maxItems:10,items:item},discountGuarani:{type:'integer',minimum:0},freightGuarani:{type:'integer',minimum:0},deliveryType:{type:'string',enum:[...SALE_DELIVERY_TYPES]},deliveryAddress:{type:'string',maxLength:500},paymentMethod:{type:'string',enum:[...SALE_PAYMENT_METHODS]},paymentReference:{type:'string',maxLength:150},notes:{type:'string',maxLength:1500}} as const;
export async function salesRoutes(app:FastifyInstance,o:Options){
 app.get('/catalog',{preHandler:requirePermission(o.authService,'sales.create'),schema:{querystring:{type:'object',additionalProperties:false,properties:{search:{type:'string',maxLength:100}}}}},async r=>o.service.catalog((r.query as {search?:string}).search));
 app.get<{Querystring:{pageSize?:number;nextToken?:string;search?:string;status?:SaleStatus;customerId?:string;paymentMethod?:SalePaymentMethod;dateFrom?:string;dateTo?:string}}>('/',{preHandler:requirePermission(o.authService,'sales.authorized.read'),schema:{querystring:{type:'object',additionalProperties:false,properties:{pageSize:{type:'integer',minimum:1,maximum:100,default:25},nextToken:{type:'string'},search:{type:'string',maxLength:180},status:{type:'string',enum:[...SALE_STATUSES]},customerId:uuid,paymentMethod:{type:'string',enum:[...SALE_PAYMENT_METHODS]},dateFrom:{type:'string',format:'date'},dateTo:{type:'string',format:'date'}}}}},async r=>{const a=authenticatedUser(r);const q=r.query;return o.service.list({limit:q.pageSize??25,...q,...(!hasPermission(a.role,'sales.read')?{userId:a.userId}:{})},hasPermission(a.role,'sales.costs.read'),hasPermission(a.role,'sales.margins.read'));});
 app.get<{Params:Id}>('/:id',{preHandler:requirePermission(o.authService,'sales.authorized.read'),schema:{params}},async r=>{const a=authenticatedUser(r);const sale=await o.service.get(r.params.id,hasPermission(a.role,'sales.costs.read'),hasPermission(a.role,'sales.margins.read'));if(!hasPermission(a.role,'sales.read')&&sale.createdBy!==a.userId)throw Object.assign(new Error('Acceso no autorizado'),{statusCode:403});return sale;});
 app.get<{Params:Id}>('/:id/costing',{preHandler:requirePermission(o.authService,'sales.costs.read'),schema:{params}},async r=>{const a=authenticatedUser(r);return o.costing.getSaleCost(r.params.id,true,hasPermission(a.role,'sales.margins.read'));});
 app.post<{Params:Id}>('/:id/retry-costing',{preHandler:requirePermission(o.authService,'sales.costs.read'),schema:{params}},async r=>o.service.retryCosting(r.params.id));
 app.post<{Body:CreateSaleRequest}>('/',{preHandler:requirePermission(o.authService,'sales.create'),schema:{body:{type:'object',additionalProperties:false,required:['saleDate','items','deliveryType','paymentMethod'],properties:fields}}},async(r,reply)=>{const a=authenticatedUser(r);return reply.status(201).send(await o.service.create(r.body,a.userId,hasPermission(a.role,'sales.discount')));});
 app.patch<{Params:Id;Body:UpdateSaleRequest}>('/:id',{preHandler:requirePermission(o.authService,'sales.update'),schema:{params,body:{type:'object',additionalProperties:false,minProperties:1,properties:fields}}},async r=>{const a=authenticatedUser(r);return o.service.update(r.params.id,r.body,a.userId,hasPermission(a.role,'sales.discount'));});
 app.post<{Params:Id}>('/:id/confirm',{preHandler:requirePermission(o.authService,'sales.confirm'),schema:{params}},async r=>o.service.confirm(r.params.id,authenticatedUser(r).userId));
 app.post<{Params:Id;Body:VoidSaleRequest}>('/:id/void',{preHandler:requirePermission(o.authService,'sales.void'),schema:{params,body:{type:'object',additionalProperties:false,required:['reason'],properties:{reason:{type:'string',minLength:1,maxLength:500}}}}},async r=>o.service.void(r.params.id,r.body.reason,authenticatedUser(r).userId));
}
