import { CUSTOMER_DOCUMENT_TYPES, CUSTOMER_STATUSES, CUSTOMER_TYPES, type CreateCustomerRequest, type CustomerStatus, type CustomerType, type UpdateCustomerRequest } from '@lcm/contracts';
import type { FastifyInstance } from 'fastify'; import type { AuthService } from '../../auth/application/auth.service.js';
import { authenticatedUser, requirePermission } from '../../auth/http/authorization.js'; import type { CustomersService } from '../application/customers.service.js';
const strings={ firstName:{type:'string',maxLength:120},lastName:{type:'string',maxLength:120},businessName:{type:'string',maxLength:180},
 documentType:{type:'string',enum:[...CUSTOMER_DOCUMENT_TYPES]},documentNumber:{type:'string',maxLength:60},taxId:{type:'string',maxLength:40},
 phone:{type:'string',maxLength:50},email:{type:'string',format:'email',maxLength:254},address:{type:'string',maxLength:300},city:{type:'string',maxLength:120},notes:{type:'string',maxLength:1500}} as const;
export async function customersRoutes(app:FastifyInstance,o:{authService:AuthService;service:CustomersService}){
 const idSchema={type:'object',required:['id'],properties:{id:{type:'string',format:'uuid'}}} as const;
 app.get<{Querystring:{pageSize?:number;nextToken?:string;search?:string;type?:CustomerType;status?:CustomerStatus;city?:string}}>('/',{preHandler:requirePermission(o.authService,'customers.read'),schema:{querystring:{type:'object',additionalProperties:false,properties:{pageSize:{type:'integer',minimum:1,maximum:100,default:25},nextToken:{type:'string',maxLength:1000},search:{type:'string',maxLength:180},type:{type:'string',enum:[...CUSTOMER_TYPES]},status:{type:'string',enum:[...CUSTOMER_STATUSES],default:'ACTIVE'},city:{type:'string',maxLength:120}}}}},r=>o.service.list({limit:r.query.pageSize??25,...(r.query.nextToken?{nextToken:r.query.nextToken}:{}),...(r.query.search?{search:r.query.search}:{}),...(r.query.type?{type:r.query.type}:{}),...(r.query.status?{status:r.query.status}:{}),...(r.query.city?{city:r.query.city}:{})}));
 app.get<{Params:{id:string}}>('/:id',{preHandler:requirePermission(o.authService,'customers.read'),schema:{params:idSchema}},r=>o.service.get(r.params.id));
 app.post<{Body:CreateCustomerRequest}>('/',{preHandler:requirePermission(o.authService,'customers.create'),schema:{body:{type:'object',additionalProperties:false,required:['type'],properties:{type:{type:'string',enum:[...CUSTOMER_TYPES]},...strings}}}},async(r,reply)=>reply.status(201).send(await o.service.create(r.body,authenticatedUser(r).userId)));
 app.patch<{Params:{id:string};Body:UpdateCustomerRequest}>('/:id',{preHandler:requirePermission(o.authService,'customers.update'),schema:{params:idSchema,body:{type:'object',additionalProperties:false,minProperties:1,properties:{...strings,type:{not:{}},id:{not:{}},status:{not:{}},createdAt:{not:{}},createdBy:{not:{}}}}}},r=>o.service.update(r.params.id,r.body,authenticatedUser(r).userId));
 app.patch<{Params:{id:string};Body:{status:CustomerStatus}}>('/:id/status',{preHandler:requirePermission(o.authService,'customers.disable'),schema:{params:idSchema,body:{type:'object',additionalProperties:false,required:['status'],properties:{status:{type:'string',enum:[...CUSTOMER_STATUSES]}}}}},r=>o.service.updateStatus(r.params.id,r.body.status,authenticatedUser(r).userId));
}
