import { FUEL_TYPES, TRUCK_STATUSES, VEHICLE_TYPES, type CreateTruckRequest, type FuelType, type TruckStatus, type UpdateTruckRequest, type VehicleType } from '@lcm/contracts';
import type { FastifyInstance } from 'fastify';
import type { AuthService } from '../../auth/application/auth.service.js'; import { authenticatedUser, requirePermission } from '../../auth/http/authorization.js'; import type { TrucksService } from '../application/trucks.service.js';
const idSchema = { type: 'object', required: ['id'], properties: { id: { type: 'string', format: 'uuid' } } } as const;
const mutable = { internalCode: { type: 'string', maxLength: 30 }, brand: { type: 'string', minLength: 1, maxLength: 100 }, model: { type: 'string', maxLength: 100 }, year: { type: 'integer', minimum: 1900, maximum: 2100 }, vehicleType: { type: 'string', enum: [...VEHICLE_TYPES] }, maxLoadKg: { type: 'integer', minimum: 1 }, maxVolumeM3: { type: 'string', pattern: '^\\d+(?:[.,]\\d{1,3})?$' }, fuelType: { type: 'string', enum: [...FUEL_TYPES] }, currentOdometerKm: { type: 'integer', minimum: 0 }, notes: { type: 'string', maxLength: 1500 } } as const;
export async function trucksRoutes(app: FastifyInstance, options: { authService: AuthService; service: TrucksService }) {
  app.get<{ Querystring: { pageSize?: number; nextToken?: string; search?: string; status?: TruckStatus; vehicleType?: VehicleType; fuelType?: FuelType } }>('/', { preHandler: requirePermission(options.authService, 'trucks.read'), schema: { querystring: { type: 'object', additionalProperties: false, properties: { pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 25 }, nextToken: { type: 'string', maxLength: 1000 }, search: { type: 'string', maxLength: 180 }, status: { type: 'string', enum: [...TRUCK_STATUSES], default: 'ACTIVE' }, vehicleType: { type: 'string', enum: [...VEHICLE_TYPES] }, fuelType: { type: 'string', enum: [...FUEL_TYPES] } } } } }, (request) => options.service.list({ limit: request.query.pageSize ?? 25, ...(request.query.nextToken ? { nextToken: request.query.nextToken } : {}), ...(request.query.search ? { search: request.query.search } : {}), ...(request.query.status ? { status: request.query.status } : {}), ...(request.query.vehicleType ? { vehicleType: request.query.vehicleType } : {}), ...(request.query.fuelType ? { fuelType: request.query.fuelType } : {}) }));
  app.get<{ Params: { id: string } }>('/:id', { preHandler: requirePermission(options.authService, 'trucks.read'), schema: { params: idSchema } }, (request) => options.service.get(request.params.id));
  app.post<{ Body: CreateTruckRequest }>('/', { preHandler: requirePermission(options.authService, 'trucks.create'), schema: { body: { type: 'object', additionalProperties: false, required: ['plate', 'brand', 'vehicleType', 'fuelType'], properties: { plate: { type: 'string', minLength: 1, maxLength: 20 }, ...mutable } } } }, async (request, reply) => reply.status(201).send(await options.service.create(request.body, authenticatedUser(request).userId)));
  app.patch<{ Params: { id: string }; Body: UpdateTruckRequest }>('/:id', { preHandler: requirePermission(options.authService, 'trucks.update'), schema: { params: idSchema, body: { type: 'object', additionalProperties: false, minProperties: 1, properties: { ...mutable, plate: { not: {} } } } } }, (request) => options.service.update(request.params.id, request.body, authenticatedUser(request).userId));
  app.patch<{ Params: { id: string }; Body: { status: TruckStatus } }>('/:id/status', { preHandler: requirePermission(options.authService, 'trucks.status.manage'), schema: { params: idSchema, body: { type: 'object', additionalProperties: false, required: ['status'], properties: { status: { type: 'string', enum: [...TRUCK_STATUSES] } } } } }, (request) => options.service.updateStatus(request.params.id, request.body.status, authenticatedUser(request).userId));
}
