import { randomBytes, randomUUID } from 'node:crypto';
import type { CreateSaleRequest, SaleCatalogResponse, SaleItemInput, SaleResponse, SalesPageResponse, UpdateSaleRequest } from '@lcm/contracts';
import type { CustomerRepository } from '../../customers/domain/customer.repository.js';
import { customerDisplayName } from '../../customers/domain/customer.js';
import type { InventoryMovement, InventoryRepository } from '../../inventory/domain/inventory.js';
import type { ProductRepository } from '../../products/domain/product.repository.js';
import type { Product, ProductPresentation } from '../../products/domain/product.js';
import type { Sale, SaleItem } from '../domain/sale.js';
import { SaleConflictError, type SaleListOptions, type SaleRepository } from '../domain/sale.repository.js';
import { SaleApplicationError } from './sale-application-error.js';
import type { FifoCostingService } from '../../costing/application/fifo-costing.service.js';
import type { CashService } from '../../cash/application/cash.service.js';

export class SalesService {
  constructor(private readonly sales: SaleRepository, private readonly products: ProductRepository, private readonly customers: CustomerRepository, private readonly inventory: InventoryRepository, private readonly costing: FifoCostingService, private readonly cash: CashService) {}
  async create(input: CreateSaleRequest, actor: string, canDiscount: boolean): Promise<SaleResponse> {
    this.validateHeader(input, canDiscount); const now=new Date().toISOString(); const items=await this.makeItems(input.items);
    const customer=await this.customer(input.customerId); const totals=totalsFor(items,input.discountGuarani??0,input.freightGuarani??0);
    const sale: Sale={id:randomUUID(),saleNumber:numberFor(now),status:'DRAFT',saleDate:input.saleDate,...customer,items,...totals,
      deliveryType:input.deliveryType,...optional('deliveryAddress',input.deliveryAddress),paymentMethod:input.paymentMethod,
      ...optional('paymentReference',input.paymentReference),...optional('notes',input.notes),costingStatus:'NOT_APPLICABLE',createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor};
    try { await this.sales.create(sale); } catch(e) { this.conflict(e); } return response(sale);
  }
  async update(id:string,input:UpdateSaleRequest,actor:string,canDiscount:boolean){const current=await this.require(id);if(current.status!=='DRAFT')throw new SaleApplicationError('Solo se puede editar una venta en borrador',409);
    const merged:CreateSaleRequest={...(input.customerId??current.customerId?{customerId:input.customerId??current.customerId}:{}),saleDate:input.saleDate??current.saleDate,items:input.items??current.items.map(i=>({productId:i.productId,presentationId:i.presentationId,quantity:i.quantity,...(i.notes?{notes:i.notes}:{})})),discountGuarani:input.discountGuarani??current.discountGuarani,freightGuarani:input.freightGuarani??current.freightGuarani,deliveryType:input.deliveryType??current.deliveryType,...(input.deliveryAddress??current.deliveryAddress?{deliveryAddress:input.deliveryAddress??current.deliveryAddress}:{}),paymentMethod:input.paymentMethod??current.paymentMethod,...(input.paymentReference??current.paymentReference?{paymentReference:input.paymentReference??current.paymentReference}:{}),...(input.notes??current.notes?{notes:input.notes??current.notes}:{})};
    this.validateHeader(merged,canDiscount);const items=await this.makeItems(merged.items);const customer=await this.customer(merged.customerId);const next:Sale={...current,...customer,items,...totalsFor(items,merged.discountGuarani??0,merged.freightGuarani??0),saleDate:merged.saleDate,deliveryType:merged.deliveryType,...optional('deliveryAddress',merged.deliveryAddress),paymentMethod:merged.paymentMethod,...optional('paymentReference',merged.paymentReference),...optional('notes',merged.notes),updatedAt:new Date().toISOString(),updatedBy:actor};try{await this.sales.replace(next,current.updatedAt);}catch(e){this.conflict(e);}return response(next);}
  async confirm(id:string,actor:string){const current=await this.require(id);if(current.status!=='DRAFT')throw new SaleApplicationError('La venta ya fue confirmada o anulada',409);if(!current.items.length)throw new SaleApplicationError('La venta debe tener al menos una línea',400);if(current.customerId)await this.customer(current.customerId);
    const now=new Date().toISOString();const financial=await this.cash.prepareSale(current,actor,'SALE_PAYMENT');const movements=this.movements(current,'SALE',actor,now);const next:Sale={...current,cashSessionId:financial.session.id,status:'CONFIRMED',costingStatus:movements.length?'PENDING':'NOT_APPLICABLE',confirmedAt:now,confirmedBy:actor,updatedAt:now,updatedBy:actor};try{await this.sales.confirm(next,movements,current.updatedAt,financial);}catch(e){this.conflict(e);}if(!movements.length)return response(next);try{return response(await this.costing.costSale(next.id));}catch{return response(next);}}
  async void(id:string,reason:string,actor:string){const current=await this.require(id);if(current.status==='VOIDED')throw new SaleApplicationError('La venta ya fue anulada',409);if(current.status!=='CONFIRMED')throw new SaleApplicationError('Solo se puede anular una venta confirmada',409);if(!reason.trim())throw new SaleApplicationError('El motivo de anulación es obligatorio',400);const financial=await this.cash.prepareSale(current,actor,'SALE_VOID');const now=new Date().toISOString();const movements=this.movements(current,'SALE_VOID',actor,now);const next:Sale={...current,status:'VOIDED',voidReason:reason.trim(),voidedAt:now,voidedBy:actor,updatedAt:now,updatedBy:actor};try{await this.sales.void(next,movements,current.updatedAt,financial);}catch(e){this.conflict(e);}try{return response(await this.costing.reverseSaleCost(next.id,actor,reason.trim()),true,true);}catch{return response(next,true,true);}}
  async get(id:string,costs=false,margins=false){return response(await this.require(id),costs,margins);}
  async list(o:SaleListOptions,costs=false,margins=false):Promise<SalesPageResponse>{const p=await this.sales.list(o);return{...p,items:p.items.map(s=>response(s,costs,margins))}}
  async retryCosting(id:string){return response(await this.costing.retrySaleCosting(id),true,true);}
  async catalog(search?:string):Promise<SaleCatalogResponse>{const page=await this.products.list({limit:100,status:'ACTIVE',...(search?{search}:{})});const balances=await this.inventory.getBalances(page.items.map(p=>p.id));const balance=new Map(balances.map(b=>[b.productId,b.onHandInternal]));const presentations=await this.products.presentationsForProducts(page.items.map(p=>p.id));const products=new Map(page.items.map(p=>[p.id,p]));return{items:presentations.filter(p=>p.status==='ACTIVE').map(p=>{const product=products.get(p.productId)!;return{productId:product.id,presentationId:p.id,code:product.code,name:product.name,presentationName:p.name,...(p.sku?{sku:p.sku}:{}),...(p.barcode?{barcode:p.barcode}:{}),unitPriceGuarani:p.salePriceGuarani,...(product.trackStock?{availableBaseInternal:balance.get(product.id)??0}:{}),trackStock:product.trackStock}})}}
  private async makeItems(inputs:readonly SaleItemInput[]):Promise<readonly SaleItem[]>{if(inputs.length>10)throw new SaleApplicationError('La venta admite hasta 10 líneas',400);return Promise.all(inputs.map(async(input,index)=>{const product=await this.products.findById(input.productId);const presentation=product&&await this.products.findPresentationById(product.id,input.presentationId);if(!product||product.status!=='ACTIVE'||!presentation||presentation.status!=='ACTIVE')throw new SaleApplicationError('Producto o presentación inactiva/no encontrada',400);const quantityBaseInternal=parseQuantity(input.quantity,presentation.baseQuantityInternal);const unitPriceGuarani=presentation.salePriceGuarani;const units=parseDecimal(input.quantity);const lineSubtotalGuarani=safeInteger((unitPriceGuarani*units.numerator)/units.denominator,'subtotal');return{id:randomUUID(),productId:product.id,presentationId:presentation.id,productSnapshot:productSnapshot(product),presentationSnapshot:presentationSnapshot(presentation),quantity:normalizeQuantity(input.quantity),quantityBaseInternal,unitPriceGuarani,lineSubtotalGuarani,...optional('notes',input.notes),sortOrder:index*10,trackStock:product.trackStock};}));}
  private async customer(id?:string){if(!id)return{};const c=await this.customers.findById(id);if(!c)throw new SaleApplicationError('Cliente no encontrado',400);if(c.status!=='ACTIVE')throw new SaleApplicationError('El cliente debe estar activo',409);return{customerId:c.id,customerSnapshot:{displayName:customerDisplayName(c),...(c.documentType?{documentType:c.documentType}:{}),...(c.documentNumber?{documentNumber:c.documentNumber}:{}),...(c.taxId?{taxId:c.taxId}:{})}};}
  private validateHeader(i:CreateSaleRequest,canDiscount:boolean){if(!/^\d{4}-\d{2}-\d{2}$/.test(i.saleDate))throw new SaleApplicationError('Fecha de venta inválida',400);if((i.discountGuarani??0)>0&&!canDiscount)throw new SaleApplicationError('No tiene permiso para aplicar descuentos',403);if(i.deliveryType!=='PICKUP'&&!i.deliveryAddress?.trim())throw new SaleApplicationError('La dirección de entrega es obligatoria',400);}
  private movements(s:Sale,type:'SALE'|'SALE_VOID',actor:string,now:string):readonly InventoryMovement[]{const grouped=new Map<string,{item:SaleItem;quantity:number}>();for(const item of s.items.filter(i=>i.trackStock)){const g=grouped.get(item.productId);grouped.set(item.productId,{item,quantity:(g?.quantity??0)+item.quantityBaseInternal});}return[...grouped.values()].map(({item,quantity})=>{const id=randomUUID();return{id,movementNumber:`MOV-${now.slice(0,4)}-${id.toUpperCase()}`,productId:item.productId,productSnapshot:item.productSnapshot,saleId:s.id,type,quantityDeltaInternal:type==='SALE'?-quantity:quantity,sourceType:type,sourceId:s.id,sourceLineId:item.productId,referenceNumber:s.saleNumber,occurredAt:now,createdAt:now,createdBy:actor};});}
  private async require(id:string){const s=await this.sales.findById(id);if(!s)throw new SaleApplicationError('Venta no encontrada',404);return s;}
  private conflict(e:unknown):never{if(e instanceof SaleConflictError)throw new SaleApplicationError(e.reason==='STOCK'?'Stock insuficiente para confirmar la venta':e.reason==='NUMBER'?'Número de venta duplicado':'La venta cambió; recargue e intente nuevamente',409);throw e;}
}
function response(s:Sale,costs=false,margins=false):SaleResponse{const {directCogsGuarani,grossProfitGuarani,grossMarginBps,netMerchandiseRevenueGuarani,...base}=s;return{...base,...(costs&&directCogsGuarani!==undefined?{directCogsGuarani}:{}),...(margins?{netMerchandiseRevenueGuarani,grossProfitGuarani,grossMarginBps}:{}),items:s.items.map(({trackStock:_track,directCogsGuarani:itemCogs,grossProfitGuarani:itemProfit,grossMarginBps:itemMargin,netRevenueGuarani,...item})=>({...item,...(costs&&itemCogs!==undefined?{directCogsGuarani:itemCogs}:{}),...(margins?{netRevenueGuarani,grossProfitGuarani:itemProfit,grossMarginBps:itemMargin}:{})}))};}
function totalsFor(items:readonly SaleItem[],discount:number,freight:number){if(!Number.isSafeInteger(discount)||discount<0||!Number.isSafeInteger(freight)||freight<0)throw new SaleApplicationError('Descuento y flete deben ser enteros no negativos',400);const subtotalGuarani=items.reduce((sum,i)=>safeInteger(sum+i.lineSubtotalGuarani,'subtotal'),0);const totalGuarani=safeInteger(subtotalGuarani-discount+freight,'total');if(totalGuarani<0)throw new SaleApplicationError('El total no puede ser negativo',400);return{subtotalGuarani,discountGuarani:discount,freightGuarani:freight,totalGuarani};}
function parseDecimal(value:string){if(!/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/.test(value)||Number(value)<=0)throw new SaleApplicationError('Cantidad inválida',400);const [whole,fraction='']=value.split('.');const denominator=10**fraction.length;return{numerator:Number(whole)*denominator+Number(fraction||0),denominator};}
function parseQuantity(value:string,base:number){const q=parseDecimal(value);return safeInteger((base*q.numerator)/q.denominator,'cantidad base');}
function normalizeQuantity(v:string){return v.includes('.')?v.replace(/0+$/,'').replace(/\.$/,''):v;}
function safeInteger(v:number,label:string){if(!Number.isSafeInteger(v))throw new SaleApplicationError(`La ${label} no puede representarse exactamente`,400);return v;}
function optional<K extends string>(key:K,value:string|undefined):Record<K,string>|Record<string,never>{const v=value?.trim();return v?{[key]:v} as Record<K,string>:{};}
function numberFor(now:string){return`VTA-${now.slice(0,4)}-${randomBytes(4).toString('hex').toUpperCase()}`;}
function productSnapshot(p:Product){return{code:p.code,name:p.name,baseUnit:p.baseUnit,quantityScale:p.quantityScale};}
function presentationSnapshot(p:ProductPresentation){return{name:p.name,...(p.sku?{sku:p.sku}:{}),baseQuantityInternal:p.baseQuantityInternal};}
