import { TransactionCanceledException } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, GetCommand, ScanCommand, TransactWriteCommand, type TransactWriteCommandInput } from '@aws-sdk/lib-dynamodb';
import type { TruckListOptions, TruckPage, TruckRepository } from '../domain/truck.repository.js';
import { TruckUniquenessError } from '../domain/truck.repository.js';
import type { Truck } from '../domain/truck.js';
const entity = 'TRUCK';
export class DynamoDbTruckRepository implements TruckRepository {
  constructor(private readonly client: DynamoDBDocumentClient, private readonly table: string) {}
  async findById(id: string) { const out = await this.client.send(new GetCommand({ TableName: this.table, Key: { pk: truckKey(id) }, ConsistentRead: true })); return fromItem(out.Item); }
  async list(o: TruckListOptions): Promise<TruckPage> { const names: Record<string,string> = { '#entity':'entityType' }; const values: Record<string,unknown> = { ':entity':entity }; const filters = ['#entity = :entity']; if (o.status) { names['#status']='status'; values[':status']=o.status; filters.push('#status = :status'); } if (o.vehicleType) { names['#vehicleType']='vehicleType'; values[':vehicleType']=o.vehicleType; filters.push('#vehicleType = :vehicleType'); } if (o.fuelType) { names['#fuelType']='fuelType'; values[':fuelType']=o.fuelType; filters.push('#fuelType = :fuelType'); } if (o.search) { names['#search']='normalizedSearch'; values[':search']=o.search; filters.push('contains(#search, :search)'); } const out = await this.client.send(new ScanCommand({ TableName: this.table, Limit: o.limit, FilterExpression: filters.join(' AND '), ExpressionAttributeNames: names, ExpressionAttributeValues: values, ...(o.nextToken ? { ExclusiveStartKey: decode(o.nextToken) } : {}) })); return { items: (out.Items ?? []).map(fromItem).filter((item): item is Truck => !!item).sort((a,b) => a.plate.localeCompare(b.plate)), ...(out.LastEvaluatedKey ? { nextToken: Buffer.from(JSON.stringify(out.LastEvaluatedKey)).toString('base64url') } : {}) }; }
  async create(truck: Truck) { try { await this.client.send(new TransactWriteCommand({ TransactItems: [{ Put: { TableName: this.table, Item: item(truck), ConditionExpression: 'attribute_not_exists(pk)' } }, lock(plateKey(truck.plate), truck.id, this.table), ...(truck.internalCode ? [lock(codeKey(truck.internalCode), truck.id, this.table)] : [])] })); } catch (error) { this.rethrow(error, truck); } }
  async update(truck: Truck, previous: Truck) { const operations: NonNullable<TransactWriteCommandInput['TransactItems']> = [{ Put: { TableName: this.table, Item: item(truck), ConditionExpression: 'attribute_exists(pk)' } }]; if (truck.internalCode !== previous.internalCode) { if (truck.internalCode) operations.push(lock(codeKey(truck.internalCode), truck.id, this.table)); if (previous.internalCode) operations.push({ Delete: { TableName: this.table, Key: { pk: codeKey(previous.internalCode) } } }); } try { await this.client.send(new TransactWriteCommand({ TransactItems: operations })); } catch (error) { this.rethrow(error, truck); } }
  private rethrow(error: unknown, truck: Truck): never { if (error instanceof TransactionCanceledException) throw new TruckUniquenessError(truck.internalCode ? 'internalCode' : 'plate'); throw error; }
}
function truckKey(id: string) { return `TRUCK#${id}`; } function plateKey(plate: string) { return `PLATE#${plate}`; } function codeKey(code: string) { return `INTERNAL_CODE#${code}`; }
function lock(pk: string, id: string, table: string) { return { Put: { TableName: table, Item: { pk, entityType: 'TRUCK_UNIQUE', truckId: id }, ConditionExpression: 'attribute_not_exists(pk)' } }; }
function item(truck: Truck) { return { pk: truckKey(truck.id), entityType: entity, status: truck.status, vehicleType: truck.vehicleType, fuelType: truck.fuelType, normalizedSearch: truck.normalizedSearch, data: truck }; }
function fromItem(value?: Record<string, unknown>): Truck | null { return value?.['entityType'] === entity ? value['data'] as Truck : null; }
function decode(token: string): Record<string, unknown> { try { const value: unknown = JSON.parse(Buffer.from(token, 'base64url').toString()); if (!value || typeof value !== 'object' || Array.isArray(value) || typeof (value as Record<string, unknown>)['pk'] !== 'string') throw new Error(); return value as Record<string, unknown>; } catch { throw Object.assign(new Error('Cursor inválido'), { statusCode: 400 }); } }
