import { randomBytes, randomUUID } from 'node:crypto';
import type { CreateTripRequest, DeliverTripRequest, StartTripRequest, TripsPageResponse, UpdateTripRequest, UserRole } from '@lcm/contracts';
import type { DriverRepository } from '../../drivers/domain/driver.repository.js';
import type { SaleRepository } from '../../sales/domain/sale.repository.js';
import type { TripLoadRepository } from '../../trip-loads/domain/trip-load.repository.js';
import type { TruckRepository } from '../../trucks/domain/truck.repository.js';
import type { Trip } from '../domain/trip.js';
import type { TripListOptions, TripRepository } from '../domain/trip.repository.js';
import { TripConflictError } from '../domain/trip.repository.js';
export class TripsService {
 constructor(private readonly repo:TripRepository,private readonly trucks:TruckRepository,private readonly drivers:DriverRepository,private readonly sales:SaleRepository,private readonly loads:TripLoadRepository){}
 async list(o:TripListOptions,user:string,role:UserRole):Promise<TripsPageResponse>{const driver=role==='DRIVER'?await this.driverForUser(user):null;if(role==='DRIVER'&&!driver)return{items:[]};const p=await this.repo.list({...o,...(driver?{driverId:driver.id}:{})});return{items:p.items,...(p.nextToken?{nextToken:p.nextToken}:{})};}
 async get(id:string,user:string,role:UserRole){const t=await this.require(id);await this.own(t,user,role);return t;}
 async create(i:CreateTripRequest,user:string){const data=await this.validate(i);const now=new Date().toISOString(),id=randomUUID();const t:Trip={id,tripNumber:`VIA-${now.slice(0,4)}-${randomBytes(4).toString('hex').toUpperCase()}`,...data,status:'DRAFT',createdAt:now,updatedAt:now,createdBy:user,updatedBy:user};await this.freight(t);await this.repo.create(t);return t;}
 async update(id:string,i:UpdateTripRequest,user:string){const old=await this.require(id);if(old.status!=='DRAFT')throw conflict('Solo un viaje borrador puede editarse');const data=await this.validate({...old,...i});const t={...old,...data,updatedAt:new Date().toISOString(),updatedBy:user};await this.freight(t);await this.repo.replace(t,old.updatedAt);return t;}
 async ready(id:string,user:string){const old=await this.require(id);if(old.status!=='DRAFT')throw conflict('El viaje no está en borrador');await this.validate(old);await this.requireConfirmedLoad(old);const t={...old,status:'READY' as const,updatedAt:new Date().toISOString(),updatedBy:user};try{await this.repo.activate(t,old.updatedAt);}catch(e){if(e instanceof TripConflictError)throw conflict('Camión o chofer ya asignado');throw e;}return t;}
 async start(id:string,i:StartTripRequest,user:string,role:UserRole){const old=await this.require(id);await this.own(old,user,role);if(old.status!=='READY')throw conflict('El viaje no está listo');await this.requireConfirmedLoad(old);const truck=await this.trucks.findById(old.truckId),driver=await this.drivers.findById(old.driverId);if(!truck||truck.status!=='ACTIVE'||i.odometerStartKm<truck.currentOdometerKm)throw conflict('Camión u odómetro de salida inválido');if(!driver||driver.status!=='ACTIVE'||!!driver.licenseExpirationDate&&driver.licenseExpirationDate<new Date().toISOString().slice(0,10))throw conflict('Chofer no disponible o licencia vencida');const now=new Date().toISOString(),t={...old,status:'IN_TRANSIT' as const,odometerStartKm:i.odometerStartKm,startedAt:now,startedBy:user,updatedAt:now,updatedBy:user};await this.repo.replace(t,old.updatedAt);return t;}
 async deliver(id:string,i:DeliverTripRequest,user:string,role:UserRole){const old=await this.require(id);await this.own(old,user,role);if(old.status!=='IN_TRANSIT'||old.odometerStartKm===undefined||i.odometerEndKm<old.odometerStartKm)throw conflict('Odómetro de llegada inválido');const truck=await this.trucks.findById(old.truckId);if(!truck||i.odometerEndKm<truck.currentOdometerKm)throw conflict('El odómetro no puede disminuir');const now=new Date().toISOString(),t:Trip={...old,status:'DELIVERED',odometerEndKm:i.odometerEndKm,distanceKm:i.odometerEndKm-old.odometerStartKm,deliveredAt:now,deliveredBy:user,...(i.notes?.trim()?{notes:i.notes.trim()}:{}),updatedAt:now,updatedBy:user};await this.repo.deliver(t,old.updatedAt,{...truck,currentOdometerKm:i.odometerEndKm,updatedAt:now,updatedBy:user});return t;}
 async cancel(id:string,reason:string,user:string){const old=await this.require(id);if(!['DRAFT','READY'].includes(old.status)||!reason.trim())throw conflict('El viaje no puede cancelarse');const load=await this.loads.findByTripId(id);if(load?.status==='CONFIRMED'){const at=new Date().toISOString();await this.loads.cancel({...load,status:'CANCELLED',cancelledAt:at,cancelledBy:user,updatedAt:at,updatedBy:user},load.updatedAt);}const now=new Date().toISOString(),t={...old,status:'CANCELLED' as const,cancelReason:reason.trim(),cancelledAt:now,cancelledBy:user,updatedAt:now,updatedBy:user};if(old.status==='READY')await this.repo.release(t,old.updatedAt);else await this.repo.replace(t,old.updatedAt);return t;}
 private async requireConfirmedLoad(t:Trip){if(t.saleId&&(await this.loads.findByTripId(t.id))?.status!=='CONFIRMED')throw conflict('El viaje comercial requiere una carga confirmada');}
 private async validate(i:CreateTripRequest){const truck=await this.trucks.findById(i.truckId),driver=await this.drivers.findById(i.driverId);if(!truck||truck.status!=='ACTIVE')throw conflict('Camión no disponible');if(!driver||driver.status!=='ACTIVE'||!!driver.licenseExpirationDate&&driver.licenseExpirationDate<new Date().toISOString().slice(0,10))throw conflict('Chofer no disponible o licencia vencida');let sale;if(i.saleId){sale=await this.sales.findById(i.saleId);if(!sale||sale.status!=='CONFIRMED'||sale.deliveryType!=='OWN_FLEET')throw conflict('La venta no admite viaje propio');}return{truckId:truck.id,truckLabel:[truck.internalCode,truck.plate].filter(Boolean).join(' / '),driverId:driver.id,driverName:[driver.firstName,driver.lastName].filter(Boolean).join(' '),...(sale?{saleId:sale.id,saleNumber:sale.saleNumber,...(sale.customerSnapshot?{customerSnapshot:{displayName:sale.customerSnapshot.displayName}}:{})}:{}),originName:i.originName?.trim()||'La Casa del Material',...(i.originAddress?.trim()?{originAddress:i.originAddress.trim()}:{}),destinationName:i.destinationName.trim(),destinationAddress:i.destinationAddress.trim(),...(i.destinationCity?.trim()?{destinationCity:i.destinationCity.trim()}:{}),scheduledDate:i.scheduledDate,freightChargeGuarani:i.freightChargeGuarani??0,...(i.notes?.trim()?{notes:i.notes.trim()}:{})};}
 private async freight(t:Trip){if(t.freightChargeGuarani<0||!Number.isInteger(t.freightChargeGuarani))throw conflict('Flete inválido');if(t.saleId){const s=await this.sales.findById(t.saleId);if(!s||await this.repo.sumFreight(t.saleId,t.id)+t.freightChargeGuarani>s.freightGuarani)throw conflict('El flete asignado excede el de la venta');}}
 private async require(id:string){const t=await this.repo.findById(id);if(!t)throw Object.assign(new Error('Viaje no encontrado'),{statusCode:404});return t;}
 private async driverForUser(user:string){let token:string|undefined;do{const p=await this.drivers.list({limit:100,today:new Date().toISOString().slice(0,10),...(token?{nextToken:token}:{})});const d=p.items.find(x=>x.userId===user);if(d)return d;token=p.nextToken;}while(token);return null;}
 private async own(t:Trip,user:string,role:UserRole){if(role==='DRIVER'&&(await this.driverForUser(user))?.id!==t.driverId)throw Object.assign(new Error('Acceso no autorizado'),{statusCode:403});}
}
function conflict(message:string){return Object.assign(new Error(message),{statusCode:409});}
