import{randomUUID}from'node:crypto';import type{CreateDriverRequest,DriverResponse,DriversPageResponse,DriverStatus,UpdateDriverRequest,UserResponse}from'@lcm/contracts';import type{UserRepository}from'../../users/domain/user.repository.js';import type{DriverListOptions,DriverRepository}from'../domain/driver.repository.js';import{DriverUniquenessError}from'../domain/driver.repository.js';import{driverDisplayName,type Driver}from'../domain/driver.js';
export class DriversService{constructor(private readonly repository:DriverRepository,private readonly users:UserRepository){}
 async list(options:Omit<DriverListOptions,'today'>):Promise<DriversPageResponse>{const page=await this.repository.list({...options,...(options.search?{search:normalize(options.search)}:{}),today:today()});return{items:await Promise.all(page.items.map(d=>this.response(d))),...(page.nextToken?{nextToken:page.nextToken}:{})};}
 async get(id:string){return this.response(await this.require(id));}
 async eligibleUsers():Promise<readonly UserResponse[]>{const result:UserResponse[]=[];let token:string|undefined;do{const page=await this.users.list(100,token);for(const u of page.items)if(u.role==='DRIVER'&&u.status==='ACTIVE')result.push({id:u.id,name:u.name,username:u.username,email:u.email,role:u.role,status:u.status,createdAt:u.createdAt,updatedAt:u.updatedAt});token=page.nextToken;}while(token);return result;}
 async create(input:CreateDriverRequest,actor:string){const fields=clean(input);await this.validateUser(fields.userId);const now=new Date().toISOString();const driver:Driver={id:randomUUID(),...fields,status:'ACTIVE',normalizedSearch:search(fields),createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor};try{await this.repository.create(driver);}catch(e){rethrow(e);}return this.response(driver);}
 async update(id:string,input:UpdateDriverRequest,actor:string){const current=await this.require(id);const fields=clean({...current,...input});await this.validateUser(fields.userId);const updated:Driver={id:current.id,...fields,status:current.status,normalizedSearch:search(fields),createdAt:current.createdAt,createdBy:current.createdBy,updatedAt:new Date().toISOString(),updatedBy:actor};try{await this.repository.update(updated,current);}catch(e){rethrow(e);}return this.response(updated);}
 async updateStatus(id:string,status:DriverStatus,actor:string){const current=await this.require(id),updated={...current,status,updatedAt:new Date().toISOString(),updatedBy:actor};await this.repository.update(updated,current);return this.response(updated);}
 private async validateUser(userId?:string){if(!userId)return;const user=await this.users.findById(userId);if(!user)throw err('Usuario no encontrado',400);if(user.role!=='DRIVER'||user.status!=='ACTIVE')throw err('El usuario debe estar activo y tener rol DRIVER',400);}
 private async require(id:string){const value=await this.repository.findById(id);if(!value)throw err('Chofer no encontrado',404);return value;}
 private async response(d:Driver):Promise<DriverResponse>{const user=d.userId?await this.users.findById(d.userId):null;return{id:d.id,...(d.userId?{userId:d.userId}:{}),...(user?{user:{id:user.id,username:user.username,status:user.status}}:{}),firstName:d.firstName,...(d.lastName?{lastName:d.lastName}:{}),displayName:driverDisplayName(d),...(d.documentNumber?{documentNumber:d.documentNumber}:{}),...(d.phone?{phone:d.phone}:{}),...(d.licenseNumber?{licenseNumber:d.licenseNumber}:{}),...(d.licenseCategory?{licenseCategory:d.licenseCategory}:{}),...(d.licenseExpirationDate?{licenseExpirationDate:d.licenseExpirationDate}:{}),licenseExpired:!!d.licenseExpirationDate&&d.licenseExpirationDate<today(),status:d.status,...(d.notes?{notes:d.notes}:{}),createdAt:d.createdAt,updatedAt:d.updatedAt};}}
function clean(input:CreateDriverRequest):Omit<Driver,'id'|'status'|'normalizedSearch'|'createdAt'|'updatedAt'|'createdBy'|'updatedBy'>{const firstName=opt(input.firstName);if(!firstName)throw err('El nombre es obligatorio',400);const userId=opt(input.userId),lastName=opt(input.lastName),documentNumber=compact(input.documentNumber),phone=opt(input.phone),licenseNumber=compact(input.licenseNumber)?.toUpperCase(),licenseCategory=opt(input.licenseCategory),licenseExpirationDate=opt(input.licenseExpirationDate),notes=opt(input.notes);if(licenseExpirationDate&&!/^\d{4}-\d{2}-\d{2}$/.test(licenseExpirationDate))throw err('La fecha de vencimiento no es válida',400);return{firstName,...(userId?{userId}:{}),...(lastName?{lastName}:{}),...(documentNumber?{documentNumber}:{}),...(phone?{phone}:{}),...(licenseNumber?{licenseNumber}:{}),...(licenseCategory?{licenseCategory}:{}),...(licenseExpirationDate?{licenseExpirationDate}:{}),...(notes?{notes}:{})};}
function search(v:Pick<Driver,'firstName'|'lastName'|'documentNumber'|'phone'|'licenseNumber'>){return normalize([v.firstName,v.lastName,v.documentNumber,v.phone,v.licenseNumber].filter(Boolean).join(' '));}function opt(v?:string){return v?.trim().replace(/\s+/g,' ')||undefined;}function compact(v?:string){return v?.toUpperCase().replace(/\s+/g,'')||undefined;}function normalize(v:string){return v.trim().toLocaleLowerCase('es').replace(/\s+/g,' ');}function today(){return new Date().toISOString().slice(0,10);}function rethrow(e:unknown):never{if(e instanceof DriverUniquenessError)throw err(e.field==='userId'?'El usuario ya está asociado a otro chofer':e.field==='documentNumber'?'El documento ya está registrado':'La licencia ya está registrada',409);throw e;}function err(message:string,statusCode:number){return Object.assign(new Error(message),{statusCode});}
