import{FUEL_STATUSES,FUEL_TYPES,type CreateFuelTransactionRequest,type FuelStatus,type VoidFuelTransactionRequest}from'@lcm/contracts';
import type{FastifyInstance}from'fastify';import type{AuthService}from'../../auth/application/auth.service.js';import{authenticatedUser,requirePermission}from'../../auth/http/authorization.js';import type{FuelService}from'../application/fuel.service.js';
const uuid={type:'string',format:'uuid'}as const,id={type:'object',required:['id'],properties:{id:uuid}}as const;
export async function fuelRoutes(app:FastifyInstance,o:{authService:AuthService;service:FuelService}){
 app.get<{Querystring:{pageSize?:number;nextToken?:string;truckId?:string;tripId?:string;driverId?:string;status?:FuelStatus;dateFrom?:string;dateTo?:string;stationName?:string}}>('/',{preHandler:requirePermission(o.authService,'fuel.read'),schema:{querystring:{type:'object',additionalProperties:false,properties:{pageSize:{type:'integer',minimum:1,maximum:100,default:25},nextToken:{type:'string'},truckId:uuid,tripId:uuid,driverId:uuid,status:{type:'string',enum:[...FUEL_STATUSES]},dateFrom:{type:'string',format:'date-time'},dateTo:{type:'string',format:'date-time'},stationName:{type:'string',maxLength:150}}}}},r=>{const a=authenticatedUser(r);return o.service.list({limit:r.query.pageSize??25,...r.query},a.userId,a.role);});
 app.get<{Params:{id:string}}>('/:id',{preHandler:requirePermission(o.authService,'fuel.read'),schema:{params:id}},r=>{const a=authenticatedUser(r);return o.service.get(r.params.id,a.userId,a.role);});
 app.post<{Body:CreateFuelTransactionRequest}>('/',{preHandler:requirePermission(o.authService,'fuel.create'),schema:{body:{type:'object',additionalProperties:false,required:['truckId','liters','pricePerLiterGuarani','odometerKm','occurredAt'],properties:{truckId:uuid,tripId:uuid,driverId:uuid,fuelType:{type:'string',enum:[...FUEL_TYPES]},liters:{type:'string',pattern:'^\\d+(?:[.,]\\d{1,3})?$'},pricePerLiterGuarani:{type:'integer',minimum:0,maximum:9000000000000},odometerKm:{type:'integer',minimum:0},stationName:{type:'string',maxLength:150},supplierTaxId:{type:'string',maxLength:50},receiptNumber:{type:'string',maxLength:100},notes:{type:'string',maxLength:1000},occurredAt:{type:'string',format:'date-time'}}}}},async(r,reply)=>{const a=authenticatedUser(r);return reply.status(201).send(await o.service.create(r.body,a.userId,a.role));});
 app.post<{Params:{id:string};Body:VoidFuelTransactionRequest}>('/:id/void',{preHandler:requirePermission(o.authService,'fuel.void'),schema:{params:id,body:{type:'object',additionalProperties:false,required:['reason'],properties:{reason:{type:'string',minLength:1,maxLength:500}}}}},r=>o.service.void(r.params.id,r.body.reason,authenticatedUser(r).userId));
 app.get<{Params:{id:string};Querystring:{dateFrom?:string;dateTo?:string}}>('/truck/:id/summary',{preHandler:requirePermission(o.authService,'fuel.read'),schema:{params:id}},r=>{const a=authenticatedUser(r);return o.service.truckSummary(r.params.id,r.query.dateFrom,r.query.dateTo,a.userId,a.role);});
 app.get<{Params:{id:string}}>('/trip/:id/summary',{preHandler:requirePermission(o.authService,'fuel.read'),schema:{params:id}},r=>{const a=authenticatedUser(r);return o.service.tripSummary(r.params.id,a.userId,a.role);});
}
export async function truckFuelRoutes(app:FastifyInstance,o:{authService:AuthService;service:FuelService}){app.get<{Params:{id:string};Querystring:{dateFrom?:string;dateTo?:string}}>('/:id/fuel-summary',{preHandler:requirePermission(o.authService,'fuel.read'),schema:{params:id,querystring:{type:'object',additionalProperties:false,properties:{dateFrom:{type:'string',format:'date-time'},dateTo:{type:'string',format:'date-time'}}}}},r=>{const a=authenticatedUser(r);return o.service.truckSummary(r.params.id,r.query.dateFrom,r.query.dateTo,a.userId,a.role);});}
