import { hasPermission, type CashSessionStatus } from '@lcm/contracts';
import type { FastifyInstance } from 'fastify';
import type { AuthService } from '../../auth/application/auth.service.js';
import { authenticatedUser, requirePermission } from '../../auth/http/authorization.js';
import type { CashService } from '../application/cash.service.js';
interface Options { authService: AuthService; service: CashService }
interface Id { readonly id: string }
const params = { type: 'object', required: ['id'], properties: { id: { type: 'string', format: 'uuid' } } } as const;
const manualBody = { type: 'object', additionalProperties: false, required: ['amountGuarani', 'reason'], properties: { amountGuarani: { type: 'integer', minimum: 1 }, reason: { type: 'string', minLength: 1, maxLength: 300 }, notes: { type: 'string', maxLength: 500 } } } as const;
export async function cashRoutes(app: FastifyInstance, options: Options) {
  app.get('/sessions/current', { preHandler: requirePermission(options.authService, 'cash.read') }, (request) => options.service.current(authenticatedUser(request).userId));
  app.post<{ Body: { openingCashGuarani: number; notes?: string } }>('/sessions/open', { preHandler: requirePermission(options.authService, 'cash.open'), schema: { body: { type: 'object', additionalProperties: false, required: ['openingCashGuarani'], properties: { openingCashGuarani: { type: 'integer', minimum: 0 }, notes: { type: 'string', maxLength: 500 } } } } }, async (request, reply) => reply.status(201).send(await options.service.open(request.body.openingCashGuarani, request.body.notes, authenticatedUser(request).userId)));
  app.get<{ Querystring: { pageSize?: number; nextToken?: string; status?: CashSessionStatus; openedBy?: string } }>('/sessions', { preHandler: requirePermission(options.authService, 'cash.read') }, (request) => { const actor = authenticatedUser(request); return options.service.list({ limit: request.query.pageSize ?? 25, ...request.query }, actor.userId, hasPermission(actor.role, 'cash.audit')); });
  app.get<{ Params: Id }>('/sessions/:id', { preHandler: requirePermission(options.authService, 'cash.read'), schema: { params } }, (request) => { const actor = authenticatedUser(request); return options.service.get(request.params.id, actor.userId, hasPermission(actor.role, 'cash.audit')); });
  app.get<{ Params: Id }>('/sessions/:id/movements', { preHandler: requirePermission(options.authService, 'cash.read'), schema: { params } }, (request) => { const actor = authenticatedUser(request); return options.service.movements(request.params.id, actor.userId, hasPermission(actor.role, 'cash.audit')); });
  app.get<{ Params: Id }>('/sessions/:id/summary', { preHandler: requirePermission(options.authService, 'cash.read'), schema: { params } }, (request) => { const actor = authenticatedUser(request); return options.service.summary(request.params.id, actor.userId, hasPermission(actor.role, 'cash.audit')); });
  app.post<{ Params: Id; Body: { countedCashGuarani: number; notes?: string } }>('/sessions/:id/close', { preHandler: requirePermission(options.authService, 'cash.close'), schema: { params, body: { type: 'object', additionalProperties: false, required: ['countedCashGuarani'], properties: { countedCashGuarani: { type: 'integer', minimum: 0 }, notes: { type: 'string', maxLength: 500 } } } } }, (request) => { const actor = authenticatedUser(request); return options.service.close(request.params.id, request.body.countedCashGuarani, request.body.notes, actor.userId, hasPermission(actor.role, 'cash.audit')); });
  app.post<{ Params: Id; Body: { amountGuarani: number; reason: string; notes?: string } }>('/sessions/:id/manual-in', { preHandler: requirePermission(options.authService, 'cash.manual_in'), schema: { params, body: manualBody } }, (request) => options.service.manual(request.params.id, request.body.amountGuarani, request.body.reason, request.body.notes, authenticatedUser(request).userId, 'MANUAL_IN'));
  app.post<{ Params: Id; Body: { amountGuarani: number; reason: string; notes?: string } }>('/sessions/:id/manual-out', { preHandler: requirePermission(options.authService, 'cash.manual_out'), schema: { params, body: manualBody } }, (request) => options.service.manual(request.params.id, request.body.amountGuarani, request.body.reason, request.body.notes, authenticatedUser(request).userId, 'MANUAL_OUT'));
}
