import{randomUUID}from'node:crypto';import type{SaleCostingResponse}from'@lcm/contracts';import type{ReceivingRepository}from'../../receiving/domain/receiving.repository.js';import type{PurchaseLot}from'../../receiving/domain/receiving.js';import type{Sale,SaleItem}from'../../sales/domain/sale.js';import type{SaleRepository}from'../../sales/domain/sale.repository.js';import{marginBps,proportionalCost,proportionalShares,type LotCostBalance,type SaleLotAllocation}from'../domain/costing.js';import{CostingConflictError,type CostingRepository}from'../domain/costing.repository.js';
export class FifoCostingService{constructor(private readonly costing:CostingRepository,private readonly receiving:ReceivingRepository,private readonly sales:SaleRepository){}
 async costSale(saleId:string):Promise<Sale>{let sale=await this.requireSale(saleId);if(sale.status!=='CONFIRMED'||sale.costingStatus==='COSTED'||sale.costingStatus==='NOT_APPLICABLE')return sale;for(const item of sale.items.filter(i=>i.trackStock)){await this.ensureProductBalances(item.productId);let done=(await this.active(sale.id,item.id)).reduce((s,a)=>s+a.quantityBaseInternal,0);while(done<item.quantityBaseInternal){let allocated=false;for(const balance of await this.costing.openLots(item.productId)){if(done>=item.quantityBaseInternal)break;const take=Math.min(item.quantityBaseInternal-done,balance.remainingQuantityBaseInternal);if(take<=0)continue;try{await this.allocate(sale,item,balance,take);done+=take;allocated=true;}catch(e){if(!(e instanceof CostingConflictError))throw e;allocated=true;break;}}if(!allocated)throw new Error(`Cantidad FIFO insuficiente para ${item.productSnapshot.name}`);}}
  sale=await this.requireSale(saleId);const projected=await this.project(sale);await this.sales.replace(projected,sale.updatedAt);return projected;}
 async retrySaleCosting(id:string){return this.costSale(id);}
 async reverseSaleCost(id:string,actor:string,reason:string):Promise<Sale>{const sale=await this.requireSale(id);const now=new Date().toISOString();await this.costing.reverseSale(id,actor,reason,now);const next:Sale={...sale,costingStatus:'VOIDED',updatedAt:now,updatedBy:actor};await this.sales.replace(next,sale.updatedAt);return next;}
 async getSaleCost(id:string,costs:boolean,margins:boolean):Promise<SaleCostingResponse>{const sale=await this.requireSale(id);const allocations=await this.costing.allocationsBySale(id);return{saleId:id,costingStatus:sale.costingStatus,items:sale.items.map(i=>({saleItemId:i.id,productName:i.productSnapshot.name,quantityBaseInternal:i.quantityBaseInternal,...(margins&&i.netRevenueGuarani!==undefined?{netRevenueGuarani:i.netRevenueGuarani}:{}),...(margins&&i.grossProfitGuarani!==undefined?{grossProfitGuarani:i.grossProfitGuarani}:{}),...(margins&&i.grossMarginBps!==undefined?{grossMarginBps:i.grossMarginBps}:{}),...(costs&&i.directCogsGuarani!==undefined?{directCogsGuarani:i.directCogsGuarani}:{}),...(costs?{allocations:allocations.filter(a=>a.saleItemId===i.id)}:{})}))};}
 private async allocate(sale:Sale,item:SaleItem,balance:LotCostBalance,take:number){for(let attempt=0;attempt<3;attempt++){const current=attempt?await this.costing.getBalance(balance.lotId):balance;if(!current||current.remainingQuantityBaseInternal<take)throw new CostingConflictError();const cost=proportionalCost(current.totalCostGuarani,current.originalQuantityBaseInternal,current.allocatedQuantityBaseInternal,take);const now=new Date().toISOString();const allocation:SaleLotAllocation={id:`${item.id}#${current.lotId}`,saleId:sale.id,saleItemId:item.id,productId:item.productId,lotId:current.lotId,lotNumber:current.lotNumber,quantityBaseInternal:take,costGuarani:cost,lotReceivedAt:current.receivedAt,status:'ACTIVE',createdAt:now};const next={...current,allocatedQuantityBaseInternal:current.allocatedQuantityBaseInternal+take,remainingQuantityBaseInternal:current.remainingQuantityBaseInternal-take,allocatedCostGuarani:current.allocatedCostGuarani+cost,version:current.version+1,updatedAt:now};try{await this.costing.allocate(allocation,next,current.version);return;}catch(e){if(!(e instanceof CostingConflictError)||attempt===2)throw e;}}}
 private async project(sale:Sale):Promise<Sale>{const discounts=proportionalShares(sale.discountGuarani,sale.items.map(i=>i.lineSubtotalGuarani));const items=await Promise.all(sale.items.map(async(item,index)=>{const directCogsGuarani=item.trackStock?(await this.active(sale.id,item.id)).reduce((s,a)=>s+a.costGuarani,0):0;const allocatedDiscountGuarani=discounts[index]??0;const netRevenueGuarani=item.lineSubtotalGuarani-allocatedDiscountGuarani;const grossProfitGuarani=netRevenueGuarani-directCogsGuarani;const margin=marginBps(grossProfitGuarani,netRevenueGuarani);return{...item,allocatedDiscountGuarani,netRevenueGuarani,directCogsGuarani,grossProfitGuarani,...(margin===undefined?{}:{grossMarginBps:margin})};}));const directCogsGuarani=items.reduce((s,i)=>s+(i.directCogsGuarani??0),0);const netMerchandiseRevenueGuarani=sale.subtotalGuarani-sale.discountGuarani;const grossProfitGuarani=netMerchandiseRevenueGuarani-directCogsGuarani;const margin=marginBps(grossProfitGuarani,netMerchandiseRevenueGuarani);const now=new Date().toISOString();return{...sale,items,costingStatus:items.some(i=>i.trackStock)?'COSTED':'NOT_APPLICABLE',netMerchandiseRevenueGuarani,directCogsGuarani,grossProfitGuarani,...(margin===undefined?{}:{grossMarginBps:margin}),costedAt:now,updatedAt:now};}
 private async active(saleId:string,itemId:string){return(await this.costing.allocationsBySale(saleId)).filter(a=>a.saleItemId===itemId&&a.status==='ACTIVE');}
 private async ensureProductBalances(productId:string){let token:string|undefined;do{const page=await this.receiving.listLots({limit:100,productId,...(token?{nextToken:token}:{})});for(const lot of page.items)await this.costing.putBalanceIfAbsent(balanceFromLot(lot));token=page.nextToken;}while(token);}
 private async requireSale(id:string){const sale=await this.sales.findById(id);if(!sale)throw Object.assign(new Error('Venta no encontrada'),{statusCode:404});return sale;}
}
function balanceFromLot(lot:PurchaseLot):LotCostBalance{return{lotId:lot.id,lotNumber:lot.lotNumber,productId:lot.productId,originalQuantityBaseInternal:lot.receivedQuantityBaseInternal,allocatedQuantityBaseInternal:0,remainingQuantityBaseInternal:lot.receivedQuantityBaseInternal,allocatedCostGuarani:0,totalCostGuarani:lot.directPurchaseCostGuarani,receivedAt:lot.receivedAt,version:0,updatedAt:lot.createdAt};}
