import { DecimalPipe, KeyValuePipe } from '@angular/common'; import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core'; import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms'; import { RouterLink } from '@angular/router';
import { FUEL_TYPE_LABELS, TRUCK_STATUS_LABELS, VEHICLE_TYPE_LABELS, type CreateTruckRequest, type FuelType, type TruckResponse, type TruckStatus, type UpdateTruckRequest, type VehicleType } from '@lcm/contracts'; import { debounceTime, distinctUntilChanged, finalize } from 'rxjs'; import { PermissionService } from '../../core/permissions/permission.service'; import { TrucksApiService } from './trucks-api.service';
@Component({ selector: 'lcm-trucks', imports: [ReactiveFormsModule, RouterLink, DecimalPipe, KeyValuePipe], templateUrl: './trucks.component.html', styleUrl: './trucks.component.css', changeDetection: ChangeDetectionStrategy.OnPush })
export class TrucksComponent {
  private readonly api = inject(TrucksApiService); private readonly fb = inject(NonNullableFormBuilder); private readonly permissions = inject(PermissionService);
  readonly vehicleLabels = VEHICLE_TYPE_LABELS; readonly fuelLabels = FUEL_TYPE_LABELS; readonly statusLabels = TRUCK_STATUS_LABELS;
  readonly items = signal<readonly TruckResponse[]>([]); readonly nextToken = signal<string | null>(null); readonly loading = signal(false); readonly saving = signal(false); readonly error = signal<string | null>(null); readonly success = signal<string | null>(null); readonly mode = signal<'create'|'edit'|null>(null); readonly selected = signal<TruckResponse|null>(null); readonly statusTarget = signal<TruckResponse|null>(null); readonly targetStatus = signal<TruckStatus>('ACTIVE');
  readonly canCreate = this.permissions.has('trucks.create'); readonly canUpdate = this.permissions.has('trucks.update'); readonly canStatus = this.permissions.has('trucks.status.manage');
  readonly search = this.fb.control(''); readonly statusFilter = this.fb.control<'ALL'|TruckStatus>('ACTIVE'); readonly typeFilter = this.fb.control<'ALL'|VehicleType>('ALL'); readonly fuelFilter = this.fb.control<'ALL'|FuelType>('ALL');
  readonly form = this.fb.group({ plate: ['', [Validators.required, Validators.maxLength(20)]], internalCode: ['', Validators.maxLength(30)], brand: ['', [Validators.required, Validators.maxLength(100)]], model: ['', Validators.maxLength(100)], year: [''], vehicleType: this.fb.control<VehicleType>('TRUCK'), maxLoadKg: [''], maxVolumeM3: [''], fuelType: this.fb.control<FuelType>('DIESEL'), currentOdometerKm: ['0'], notes: ['', Validators.maxLength(1500)] });
  constructor() { this.search.valueChanges.pipe(debounceTime(350), distinctUntilChanged()).subscribe(() => this.load(true)); this.statusFilter.valueChanges.subscribe(() => this.load(true)); this.typeFilter.valueChanges.subscribe(() => this.load(true)); this.fuelFilter.valueChanges.subscribe(() => this.load(true)); this.load(true); }
  load(reset = false) { if (this.loading()) return; this.loading.set(true); this.error.set(null); this.api.list({ pageSize: 25, ...(!reset && this.nextToken() ? { nextToken: this.nextToken()! } : {}), ...(this.search.value.trim() ? { search: this.search.value.trim() } : {}), ...(this.statusFilter.value === 'ALL' ? {} : { status: this.statusFilter.value }), ...(this.typeFilter.value === 'ALL' ? {} : { vehicleType: this.typeFilter.value }), ...(this.fuelFilter.value === 'ALL' ? {} : { fuelType: this.fuelFilter.value }) }).pipe(finalize(() => this.loading.set(false))).subscribe({ next: (page) => { this.items.set(reset ? page.items : [...this.items(), ...page.items]); this.nextToken.set(page.nextToken ?? null); }, error: () => this.error.set('Error al cargar camiones.') }); }
  openCreate() { this.form.reset(empty()); this.form.controls.plate.enable(); this.selected.set(null); this.mode.set('create'); this.clear(); }
  openEdit(truck: TruckResponse) { this.form.reset({ plate: truck.plate, internalCode: truck.internalCode ?? '', brand: truck.brand, model: truck.model ?? '', year: truck.year ? String(truck.year) : '', vehicleType: truck.vehicleType, maxLoadKg: truck.maxLoadKg ? String(truck.maxLoadKg) : '', maxVolumeM3: truck.maxVolumeM3 ?? '', fuelType: truck.fuelType, currentOdometerKm: String(truck.currentOdometerKm), notes: truck.notes ?? '' }); this.form.controls.plate.disable(); this.selected.set(truck); this.mode.set('edit'); this.clear(); }
  save() { if (this.form.invalid) { this.form.markAllAsTouched(); this.error.set('Completa la chapa y la marca.'); return; } const raw = this.form.getRawValue(); const payload = clean(raw); const editing = this.mode() === 'edit'; if (editing) delete payload['plate']; this.saving.set(true); const request = editing ? this.api.update(this.selected()?.id ?? '', payload as UpdateTruckRequest) : this.api.create(payload as unknown as CreateTruckRequest); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.mode.set(null); this.success.set(editing ? 'Camión actualizado.' : 'Camión creado.'); this.load(true); }, error: (error: { error?: { message?: string } }) => this.error.set(error.error?.message ?? 'No fue posible guardar el camión.') }); }
  requestStatus(truck: TruckResponse, status: TruckStatus) { this.statusTarget.set(truck); this.targetStatus.set(status); this.clear(); }
  confirmStatus() { const truck = this.statusTarget(); if (!truck) return; this.saving.set(true); this.api.status(truck.id, this.targetStatus()).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.statusTarget.set(null); this.success.set('Estado actualizado.'); this.load(true); }, error: () => this.error.set('No fue posible cambiar el estado.') }); }
  close() { if (!this.saving()) this.mode.set(null); } cancelStatus() { this.statusTarget.set(null); }
  private clear() { this.error.set(null); this.success.set(null); }
}
function empty() { return { plate: '', internalCode: '', brand: '', model: '', year: '', vehicleType: 'TRUCK' as VehicleType, maxLoadKg: '', maxVolumeM3: '', fuelType: 'DIESEL' as FuelType, currentOdometerKm: '0', notes: '' }; }
function clean(value: ReturnType<typeof empty>): Record<string, string|number> { const output: Record<string,string|number> = { plate: value.plate.trim(), brand: value.brand.trim(), vehicleType: value.vehicleType, fuelType: value.fuelType, currentOdometerKm: Number(value.currentOdometerKm || 0) }; for (const key of ['internalCode','model','maxVolumeM3','notes'] as const) if (value[key].trim()) output[key] = value[key].trim().replace(',', key === 'maxVolumeM3' ? '.' : ','); for (const key of ['year','maxLoadKg'] as const) if (value[key]) output[key] = Number(value[key]); return output; }
